/**
 * Schalen voor Golflengte.
 *
 * Een goede schaal heeft twee uitersten waar iedereen hetzelfde beeld bij
 * heeft, en genoeg ruimte ertussen om over te twisten. "Koud - heet" werkt;
 * "goed - slecht" niet, want dat is bij iedereen anders.
 *
 * De pittige schalen onderaan zijn waar dit spel om gaat. Bij "klein - groot"
 * leg je het gewoon ergens neer; bij "preuts - schaamteloos" moet de hele
 * tafel het over iemands grens eens zien te worden, en dáár komt de discussie
 * van waar je het spel voor speelt.
 */
export interface Schaal {
  links: string
  rechts: string
}

export const SCHALEN: Schaal[] = [
  { links: 'preuts', rechts: 'schaamteloos' },
  { links: 'onschuldig', rechts: 'gênant' },
  { links: 'braaf', rechts: 'gevaarlijk' },
  { links: 'vergeeflijk', rechts: 'onvergeeflijk' },
  { links: 'nuchter', rechts: 'lam' },
  { links: 'saaie date', rechts: 'geslaagde date' },
  { links: 'red flag', rechts: 'green flag' },
  { links: 'vriendschappelijk', rechts: 'veel te close' },
  { links: 'kan door de beugel', rechts: 'echt niet meer' },
  { links: 'gewoon dronken', rechts: 'morgen sorry zeggen' },
  { links: 'onschuldig appje', rechts: 'vreemdgaan' },
  { links: 'niks aan de hand', rechts: 'relatie voorbij',},
  { links: 'zou ik doen', rechts: 'nooit van mijn leven' },
  { links: 'kan je aan je ouders vertellen', rechts: 'neem je mee in je graf' },
  { links: 'aantrekkelijk', rechts: 'afknapper' },
  { links: 'normaal op een feest', rechts: 'te ver' },
  { links: 'koud', rechts: 'heet' },
  { links: 'klein', rechts: 'groot' },
  { links: 'goedkoop', rechts: 'duur' },
  { links: 'langzaam', rechts: 'snel' },
  { links: 'stil', rechts: 'luid' },
  { links: 'zacht', rechts: 'hard' },
  { links: 'ouderwets', rechts: 'modern' },
  { links: 'saai', rechts: 'spannend' },
  { links: 'ongezond', rechts: 'gezond' },
  { links: 'gevaarlijk', rechts: 'veilig' },
  { links: 'lelijk', rechts: 'mooi' },
  { links: 'makkelijk', rechts: 'moeilijk' },
  { links: 'onbekend', rechts: 'beroemd' },
  { links: 'droog', rechts: 'nat' },
  { links: 'licht', rechts: 'zwaar' },
  { links: 'donker', rechts: 'fel' },
  { links: 'kinderachtig', rechts: 'volwassen' },
  { links: 'goor', rechts: 'lekker' },
  { links: 'nutteloos', rechts: 'onmisbaar' },
  { links: 'zeldzaam', rechts: 'overal' },
  { links: 'ontspannen', rechts: 'stressvol' },
  { links: 'schoon', rechts: 'vies' },
  { links: 'dichtbij', rechts: 'ver weg' },
  { links: 'stiekem', rechts: 'openlijk' },
  { links: 'geheim', rechts: 'algemeen bekend' },
  { links: 'goedkope date', rechts: 'dure date' },
  { links: 'huisdier', rechts: 'wild dier' },
  { links: 'ontbijt', rechts: 'avondeten' },
  { links: 'binnen', rechts: 'buiten' },
  { links: 'alleen doen', rechts: 'samen doen' },
  { links: 'guilty pleasure', rechts: 'trots op' },
  { links: 'onderschat', rechts: 'overschat' },
  { links: 'nooit gedaan', rechts: 'elke dag' },
  { links: 'zou ik nooit eten', rechts: 'zou ik elke dag eten' },
  { links: 'slecht idee', rechts: 'geniaal idee' },
  // ── tweede lading schalen ──
  { links: 'saai', rechts: 'onverantwoord' },
  { links: 'trouw', rechts: 'niet te vertrouwen' },
  { links: 'schattig', rechts: 'onweerstaanbaar' },
  { links: 'stille genieter', rechts: 'aandachtzoeker' },
  { links: 'netjes', rechts: 'smerig' },
  { links: 'kuis', rechts: 'losgeslagen' },
  { links: 'romantisch', rechts: 'puur lichamelijk' },
  { links: 'te vroeg', rechts: 'veel te laat' },
  { links: 'gezellig dronken', rechts: 'niet meer aanspreekbaar' },
  { links: 'eerlijk', rechts: 'leugenaar' },
  { links: 'nuchter gesprek', rechts: 'dronken bekentenis' },
  { links: 'vriendschappelijk', rechts: 'veel te dichtbij' },
  { links: 'onhandig', rechts: 'gênant' },
  { links: 'geheim', rechts: 'openbaar' },
  { links: 'lief appje', rechts: 'ongepast appje' },
  { links: 'één biertje', rechts: 'blackout' },
  { links: 'vergeeflijk', rechts: 'relatie voorbij' },
  { links: 'thuisblijver', rechts: 'altijd de laatste' },
  { links: 'bescheiden', rechts: 'opschepper' },
  { links: 'zuinig', rechts: 'geeft het uit aan niks' },
  { links: 'goede smaak', rechts: 'rampzalige smaak' },
  { links: 'fluisteren', rechts: 'het hele portiek wakker' },
  { links: 'jeugdzonde', rechts: 'onvergeeflijk' },
  { links: 'grappig', rechts: 'te ver gegaan' },
  { links: 'schoon', rechts: 'drie dagen dezelfde kleren' },
  { links: 'verlegen', rechts: 'schaamteloos flirten' },
  { links: 'single', rechts: 'veel te snel verliefd' },
  { links: 'gewoon moe', rechts: 'echt een kater' },
  { links: 'kleine leugen', rechts: 'alles verzwegen' },
  { links: 'vrienden', rechts: 'meer dan vrienden' },
  { links: 'netjes afgewezen', rechts: 'brutaal geghost' },
  { links: 'nette foto', rechts: 'die foto' },
  { links: 'stiekem leuk', rechts: 'openlijk verliefd' },
  { links: 'overdreven', rechts: 'echt gebeurd' },
]
