/**
 * Vragen voor "Wie van Ons".
 *
 * Deze lijst mag gerust honderden regels worden — hoe specifieker voor jullie
 * vriendengroep, hoe leuker. Voeg gewoon regels toe.
 */
export const VRAGEN: string[] = [
  'Wie belandt vanavond als eerste in bed?',
  'Wie zou een nacht in de cel overleven?',
  'Wie heeft de meest verdachte zoekgeschiedenis?',
  'Wie zou het langst volhouden zonder telefoon?',
  'Wie huilt het snelst bij een film?',
  'Wie zou als eerste opgegeten worden op een onbewoond eiland?',
  'Wie kan het slechtst tegen zijn verlies?',
  'Wie belt zijn ex na vijf biertjes?',
  'Wie is stiekem het slimst?',
  'Wie heeft de rommeligste kamer?',
  'Wie zou een goede crimineel zijn?',
  'Wie durft het minst?',
  'Wie liegt het vaakst over kleine dingen?',
  'Wie wordt het eerst rijk?',
  'Wie is het meest verslaafd aan zijn telefoon?',
  'Wie zou het langst verdwaald blijven in een stad?',
  'Wie geeft het snelst al zijn geld uit?',
  'Wie kan het beste dansen als niemand kijkt?',
  'Wie zou een sekte kunnen leiden?',
  'Wie neemt de slechtste foto’s?',
  'Wie zou als eerste betrapt worden bij een overval?',
  'Wie heeft de raarste gewoontes thuis?',
  'Wie doet het meest alsof hij iets snapt?',
  'Wie zou het langst zonder douchen kunnen?',
  'Wie praat het meest over zichzelf?',
  'Wie zou het slechtst zijn in een quiz over de anderen hier?',
  'Wie is het meest bijgelovig?',
  'Wie zou een goede ouder zijn?',
  'Wie klaagt het meest?',
  'Wie heeft de slechtste muzieksmaak?',
  'Wie zou het eerst opgeven bij een marathon?',
  'Wie kookt het slechtst?',
  'Wie zou zonder wroeging spieken op een tentamen?',
  'Wie is het vaakst te laat?',
  'Wie zou het beste kunnen liegen tegen de politie?',
  'Wie is het snelst beledigd?',
  'Wie doet de gekste dingen als hij dronken is?',
  'Wie zou het langst stil kunnen blijven?',
  'Wie heeft de meeste geheimen?',
  'Wie zou als eerste in een horrorfilm doodgaan?',
  'Wie geeft de beste adviezen?',
  'Wie neemt de meeste selfies?',
  'Wie zou een goede spion zijn?',
  'Wie is het meest gehecht aan zijn moeder?',
  'Wie zou het snelst zijn beste vriend verraden voor geld?',
  'Wie kan het slechtst een geheim bewaren?',
  'Wie is stiekem het gelukkigst?',
  'Wie heeft de meest irritante lach?',
  'Wie zou het beste in een reality-show passen?',
  'Wie doet het vaakst alsof hij luistert?',
]
