/**
 * Vragen voor "Wie van Ons".
 *
 * Bewust allemaal aan de pittige kant: dit is het spel waar de tafel gaat
 * gillen, en dat lukt niet met "wie is het vaakst te laat". Het gaat over
 * daten, flirten, exen en wat je op je telefoon hebt staan.
 *
 * Twee dingen die ze allemaal gemeen hebben, en waar je op moet letten als je
 * er zelf bij schrijft:
 *
 * · Het blijft bij "wie zou" en bij reputatie. Niemand hoeft iets te
 *   bekennen, want je stemt op een ander en niet op jezelf. Een vraag die
 *   iemand dwingt iets over zichzelf op tafel te leggen hoort hier niet.
 * · Ze zijn plagerig, niet gemeen. Je wil dat degene met de meeste stemmen
 *   lacht en drinkt, niet dat hij zich rot voelt.
 *
 * De lijst mag gerust honderden regels worden — hoe specifieker voor jullie
 * vriendengroep, hoe leuker. Voeg gewoon regels toe.
 */
export const VRAGEN: string[] = [
  'Wie zou als eerste een trio voorstellen?',
  'Wie heeft de meest verdachte zoekgeschiedenis?',
  'Wie neemt vanavond als eerste iemand mee naar huis?',
  'Wie heeft de meeste exen die nog appen?',
  'Wie heeft het vaakst iemand geghost?',
  'Wie is het slechtst in flirten?',
  'Wie flirt het meest zonder het zelf door te hebben?',
  'Wie stuurt de meeste dronken appjes naar zijn ex?',
  'Wie zou het langst zonder seks kunnen?',
  'Wie zou zijn telefoon nooit durven laten zien?',
  'Wie heeft de meeste matches en doet er niets mee?',
  'Wie zou als eerste vreemdgaan?',
  'Wie is het meest jaloers in een relatie?',
  'Wie kan het beste zoenen?',
  'Wie heeft de slechtste versiertruc?',
  'Wie zou als eerste naakt gaan zwemmen?',
  'Wie valt structureel op het verkeerde type?',
  'Wie is het snelst verliefd?',
  'Wie zou het langst volhouden op afstand?',
  'Wie zou meedoen aan Temptation Island?',
  'Wie maakt het uit via een appje?',
  'Wie heeft de meeste "het is ingewikkeld"-situaties?',
  'Wie doet het meest alsof hij ervaring heeft?',
  'Wie zou als eerste zoenen met iemand om een ander jaloers te maken?',
  'Wie heeft stiekem een oogje op iemand hier?',
  'Wie zou als eerste iets beginnen met iemand uit deze groep?',
  'Wie reageert het slechtst op een afwijzing?',
  'Wie heeft de meeste moeite met nee zeggen?',
  'Wie heeft de wildste vakantieverhalen?',
  'Wie zou het beste twee mensen tegelijk kunnen daten zonder betrapt te worden?',
  'Wie is de grootste player?',
  'Wie doet het langst over klaarmaken om uit te gaan?',
  'Wie heeft vanavond de meeste kans om te scoren?',
  'Wie gaat er als eerste stiekem vandoor met iemand?',
  'Wie is het meest onhandig op een eerste date?',
  'Wie zou als eerste ja zeggen tegen een open relatie?',
  'Wie heeft de dramatischste breakup gehad?',
  'Wie zou het langst een crush geheim houden?',
  'Wie kan het slechtst tegen flirten van anderen?',
  'Wie zou als eerste iets doen met de vriend van een ex?',
  'Wie zwicht het snelst voor een goede babbel?',
  'Wie heeft de meeste berichten teruggetrokken?',
  'Wie zou het beste iemand versieren in een taal die hij niet spreekt?',
  'Wie heeft de gênantste bijnaam gekregen van een ex?',
  'Wie zou het langst kunnen doen alsof hij single is?',
  'Wie zou een strippaal in huis zetten?',
  'Wie heeft de raarste type waar hij op valt?',
  'Wie zou als eerste iets beginnen met een collega?',
  'Wie zou zijn principes het snelst laten varen voor iemand knap?',
  'Wie heeft de meeste spijt van zijn eerste keer?',
  'Wie zou het meest overstuur zijn na een one-night stand?',
  'Wie zou als eerste een tattoo van een ex nemen?',
  'Wie heeft het vaakst gezoend met iemand van wie hij de naam kwijt was?',
  'Wie zou het eerst een date afzeggen voor deze groep?',
  'Wie is het meest chaotisch in de liefde?',
  'Wie zou als eerste meedoen aan een naaktkalender?',
  'Wie liegt het makkelijkst tegen een partner?',
  'Wie zou als eerste ja zeggen op een date met een wildvreemde?',
  'Wie heeft de meeste aanbidders die hij negeert?',
  'Wie is het beste in dirty talk?',
  'Wie heeft de meeste moeite om van iemand af te komen?',
  'Wie zou als eerste een relatie beginnen die zijn ouders haten?',
  'Wie heeft de gekste plek waar het bijna misging?',
  'Wie is het langst achter iemand aan blijven lopen die niet wilde?',
  'Wie zou als eerste zijn ex nog een kans geven?',
  'Wie heeft er het meest verborgen op zijn telefoon?',
  'Wie doet het meest moeite om er goed uit te zien voor één persoon?',
  'Wie zou als eerste iemand terugpakken na een breuk?',
  'Wie is het meest verslaafd aan de aandacht?',
  'Wie zou het snelst iets opbiechten na drie biertjes?',
  'Wie zou de slechtste bruiloftsspeech geven over zijn wilde jaren?',
  'Wie zou als eerste zoenen met iemand hier, als het mocht?',
  'Wie heeft de langste lijst van "we waren gewoon vrienden"?',
  'Wie zou het langst een slippertje stil kunnen houden?',
  'Wie wordt het snelst verliefd op iemand die niet beschikbaar is?',
  'Wie is het beste in doen alsof het hem niets doet?',
  'Wie zou als eerste weglopen bij een saaie date?',
  'Wie kan het slechtst tegen afgewezen worden in het openbaar?',
  'Wie zou als eerste zijn nummer geven aan de bediening?',
  'Wie heeft de meeste mensen gezoend op één avond?',
  'Wie zou het minst goed uitleggen wat hij gisteravond deed?',
  'Wie stuurt het eerst een berichtje dat hij morgen wil terugnemen?',
  'Wie zou als laatste toegeven dat hij verliefd is?',
  // ── tweede lading: zelfde toon, meer keuze ──
  'Wie zou als eerste meegaan naar een naaktstrand?',
  'Wie heeft de meeste nudes op zijn telefoon staan?',
  'Wie zou als eerste zijn kleren uitdoen voor geld?',
  'Wie zou het slechtst zijn in bed volgens de tafel?',
  'Wie doet alsof hij veel meer ervaring heeft dan hij heeft?',
  'Wie zou als eerste een striptease geven op een bruiloft?',
  'Wie heeft het vaakst gezoend met iemand van deze tafel?',
  'Wie zou als eerste iets beginnen met de ex van een vriend?',
  'Wie heeft de raarste kink?',
  'Wie zou als eerste toegeven dat hij verliefd is op iemand hier?',
  'Wie flirt het hardst als hij gedronken heeft?',
  'Wie heeft de meest gênante zoekgeschiedenis van deze maand?',
  'Wie zou een date afzeggen voor een voetbalwedstrijd?',
  'Wie zou het langst blijven plakken na een one-night stand?',
  'Wie vertrekt er altijd als eerste de volgende ochtend?',
  'Wie zou het minst opvallen als hij een week niet doucht?',
  'Wie laat de meeste berichten ongelezen?',
  'Wie zou als eerste op een datingshow gaan?',
  'Wie zou het meest huilen bij een romantische film?',
  'Wie heeft de meeste ongemakkelijke verhalen van vakantie?',
  'Wie zou als eerste iemand zoenen om een weddenschap?',
  'Wie doet het meest alsof hij nuchter is?',
  'Wie zou als eerste worden uitgezet bij een club?',
  'Wie heeft het vaakst ergens anders geslapen dan thuis?',
  'Wie belt als eerste zijn moeder als het misgaat?',
  'Wie zou zijn telefoon het snelst omdraaien als er iemand meekijkt?',
  'Wie zwipet het meest en spreekt het minst af?',
  'Wie zou als eerste zijn profielfoto veranderen na een breuk?',
  'Wie is het snelst jaloers?',
  'Wie zou het meest overdrijven over zijn avond?',
  'Wie heeft de meeste spijt van een tattoo?',
  'Wie zou als eerste iets doen voor een dubbeltje?',
  'Wie zou het minst betrouwbaar zijn met een geheim?',
  'Wie heeft de gekste plek waar hij gezoend heeft?',
  'Wie zou als eerste iemand meenemen naar een familiefeest?',
  'Wie kan het slechtst tegen afwijzing?',
  'Wie gaat er het vaakst alleen naar huis?',
  'Wie heeft het vaakst een blauwtje gelopen?',
  'Wie zou als eerste in de fontein springen?',
  'Wie zou een relatie verpesten met één appje?',
  'Wie heeft de meeste geheimen voor deze tafel?',
  'Wie zou als eerste vreemdgaan op vakantie?',
  'Wie zou het het langst volhouden zonder telefoon?',
  'Wie doet het meest mee aan elke gekke uitdaging?',
  'Wie is het vaakst dronken gevallen?',
  'Wie zou als eerste zijn kleren kwijtraken op een festival?',
  'Wie heeft de meest schaamteloze kroegverhalen?',
  'Wie zou als eerste zoenen in een volle bus?',
  'Wie appt de hele tafel als hij niks te doen heeft?',
  'Wie heeft de langste lijst met exen?',
  'Wie zou als eerste ruzie krijgen met een uitsmijter?',
  'Wie zou zijn huisgenoot het meest laten schrikken \'s nachts?',
  'Wie is het meest overtuigd dat hij goed kan dansen?',
  'Wie zou het eerst zwichten voor een lief berichtje?',
  'Wie heeft het gênantste liedje het meest geluisterd?',
  'Wie zou als eerste iets stelen uit een kroeg als aandenken?',
  'Wie zou het minst weten wat hij gisteren gedaan heeft?',
  'Wie doet het vaakst alsof hij het bericht niet gezien heeft?',
  'Wie zou als eerste zijn shirt uitdoen op de dansvloer?',
  'Wie heeft de meeste rare verhalen over zijn buren?',
  'Wie zou het snelst verliefd worden op vakantie?',
  'Wie zou als eerste zijn ouders tegenkomen in de kroeg?',
  'Wie heeft het vaakst gelogen over waar hij was?',
  'Wie is het eerst weg als er afgewassen moet worden?',
  'Wie zou als eerste meedoen aan een wedstrijd wie het langst zoent?',
  'Wie heeft de meeste foto\'s die nooit online mogen?',
  'Wie zou het minst kunnen zwijgen na een nacht stappen?',
  'Wie zou als eerste terugkomen bij zijn ex?',
  'Wie is het vaakst degene die alles filmt?',
  'Wie zou als eerste zijn bed uitlenen en er zelf naast liggen?',
  'Wie zou het slechtst reageren op een spraakbericht van tien minuten?',
]
