/**
 * Vragen voor Gelijk Denken.
 *
 * Een goede vraag heeft één overduidelijk antwoord dat de meeste mensen
 * geven, plus genoeg alternatieven om iemand te verleiden origineel te doen.
 * Dat is precies de val: origineel zijn kost je een slok.
 */
export const GELIJK_VRAGEN: string[] = [
  'Noem een biermerk',
  'Noem een kleur',
  'Noem een dier in de dierentuin',
  'Noem een land in Europa',
  'Noem een Nederlandse stad',
  'Noem een automerk',
  'Noem een pizzabeleg',
  'Noem een lichaamsdeel',
  'Noem een sport',
  'Noem een snack bij de snackbar',
  'Noem een fruitsoort',
  'Noem een supermarkt',
  'Noem een sociaal medium',
  'Noem een kledingstuk',
  'Noem een beroep',
  'Noem een muziekinstrument',
  'Noem een drankje met alcohol',
  'Noem een groente die niemand lekker vindt',
  'Noem iets wat in de koelkast staat',
  'Noem iets wat je meeneemt naar het strand',
  'Noem een reden om te laat te komen',
  'Noem een schoolvak',
  'Noem een huisdier',
  'Noem iets wat je op een festival ziet',
  'Noem een cocktail',
  'Noem een voetbalclub',
  'Noem een film die iedereen gezien heeft',
  'Noem een serie',
  'Noem een zanger of band',
  'Noem iets wat je doet bij verveling',
  'Noem een emoji die je vaak gebruikt',
  'Noem iets waar je bang voor bent',
  'Noem een bordspel',
  'Noem een game',
  'Noem iets wat in deze kamer staat',
  'Noem iets wat je nooit weggooit',
  'Noem een jongensnaam',
  'Noem een meisjesnaam',
  'Noem iets wat je zegt als je schrikt',
  'Noem een feestdag',
  'Noem iets wat rond is',
  'Noem een vogel',
  'Noem iets wat je op brood doet',
  'Noem een merk telefoon',
  'Noem iets wat stinkt',
  'Noem een gerecht dat je moeder maakt',
  'Noem iets wat je kwijtraakt',
  'Noem een bijnaam voor dronken zijn',
  'Noem iets wat je meeneemt naar een verjaardag',
  'Noem iets waar je te oud voor bent maar toch doet',
]
