/**
 * De verplichte woorden voor Het Verhaal.
 *
 * Elke ronde krijgt iedereen er één die in zijn zin moet. Ze zijn gekozen op
 * twee dingen tegelijk.
 *
 * Eén: er moet iets mee te lachen vallen. Hier stonden dingen als "theepot",
 * "grasmaaier" en "wasmachine", en dat is precies waarom het verhaal braaf
 * bleef. Wie "theepot" krijgt schrijft een zin over een theepot en klaar. Wie
 * "zuigzoen" of "buurmans bed" krijgt moet iets verzinnen, en dát is waar de
 * tafel om lacht.
 *
 * Twee: lastig in te proppen, maar altijd te doen. Een woord als "huis" schrijf
 * je zonder nadenken op en levert niets op; een woord waar je een bocht voor
 * moet maken brengt het verhaal ergens.
 *
 * Wat er níét in staat: werkwoorden en bijvoeglijke naamwoorden. Die glijden
 * overal in zonder dat je ze merkt. Het zijn allemaal zelfstandige naamwoorden
 * waar je iets mee moet.
 *
 * Ook niet: woorden van minder dan vijf letters. De controle plakt je zin dicht
 * en kijkt of het woord erin zit, dus 'beha' zat ook in "behalve" en 'ex' in
 * "expres". Dan is de opdracht gratis. Zie de controle in de scratchpad.
 *
 * De absurde staan er nog tussen -- een opblaaskrokodil of een tuinkabouter in
 * een verder smerig verhaal is grappiger dan nog een keer iets grofs. Maar de
 * saaie zijn eruit.
 */
export const WOORDEN: string[] = [
  // ── lijf, bed en de ochtend erna ──
  'zuigzoen',
  'tongzoen',
  'nudes',
  'dickpic',
  'condoom',
  'beugelbeha',
  'tanga',
  'boxershort',
  'schaamhaar',
  'borsthaar',
  'rugharen',
  'tepel',
  'bilspleet',
  'okselzweet',
  'voetschimmel',
  'morning-afterpil',
  'zwangerschapstest',
  'glijmiddel',
  'handboeien',
  'onderbroek',
  'matrasvlek',
  'kreun',
  'bierbuik',
  'stijve',
  'kruimeldief',
  'liefdesverdriet',
  'schaamte',
  'blaasontsteking',
  'zuigplek',
  'sekspop',

  // ── uitgaan, en wat het kost ──
  'kater',
  'braakemmer',
  'shotje',
  'tequila',
  'blackout',
  'uitsmijter',
  'danspaal',
  'afterparty',
  'kroegtijger',
  'garderobebonnetje',
  'nachtbus',
  'taxichauffeur',
  'wietlucht',
  'jointje',
  'lachgasballon',
  'energiedrank',
  'kebabzaak',
  'frituurvet',
  'kotsvlek',
  'statiegeldbon',
  'bierviltje',
  'boetezakje',
  'ontnuchtering',

  // ── daten, en wat er misgaat ──
  'ex-vriend',
  'blauwtje',
  'scharrel',
  'friendzone',
  'vrijgezellenfeest',
  'blind date',
  'openingszin',
  'groepsapp',
  'zoekgeschiedenis',
  'ongelezen bericht',
  'profielfoto',
  'schoonmoeder',
  'stiefvader',
  'huisgenoot',
  'buurmans bed',
  'wijkagent',
  'tattoo met spijt',
  'smoesje',
  'leugentje',
  'gedeelde locatie',
  'tweede telefoon',
  'slaapkamergeluid',
  'ongemakkelijke stilte',
  'afgezegde date',

  // ── plekken waar het misgaat ──
  'caravan',
  'bushokje',
  'kleedkamer',
  'invalidentoilet',
  'zolderkamer',
  'logeerbed',
  'achterbank',
  'fietsenstalling',
  'sauna',
  'naaktstrand',
  'camping',
  'festivaltent',
  'politiebureau',
  'wachtkamer',
  'tuinhuisje',
  'parkeerplaats',
  'kelder',
  'badkuip',
  'draaideur',
  'balkon',
  'dakgoot',
  'portiek',

  // ── spullen die een verhaal slopen ──
  'opblaaskrokodil',
  'pruik',
  'megafoon',
  'brandalarm',
  'bodycam',
  'beveiligingsbeeld',
  'tondeuse',
  'lijmpistool',
  'tuinslang',
  'ladder',
  'winkelwagentje',
  'sleutelbos',
  'pinpas',
  'parkeerboete',
  'krukken',
  'nekbrace',
  'toupetje',
  'waterpistool',
  'confettikanon',
  'rookmachine',

  // ── gewoon Nederlands, en juist daarom grappig ──
  'frikandel',
  'kroket',
  'bitterbal',
  'snackbar',
  'hagelslag',
  'stamppot',
  'oliebol',
  'sinterklaas',
  'kerstborrel',
  'buurtapp',
  'blauwe bak',
  'statiegeld',
  'klapstoel',
  'tuinkabouter',
  'partytent',
  'springkussen',
  'carnavalspak',
  'zwembroek',
  'hondenpoep',
  'slippers',
  'sokken in bed',
  'fietssleutel',
  'ov-chipkaart',
  'buurtbarbecue',
  // ── derde lading ──
  'bodylotion', 'scheerschuim', 'wattenstaafje', 'nagelknipper', 'pincet',
  'deodorant', 'mondwater', 'tandzijde', 'kruidenthee', 'pleister',
  'ijszak', 'thermometer', 'neusspray', 'hoestdrank', 'vitaminepil',
  'slaappil', 'oordopjes', 'slaapmasker', 'wekkerlied', 'snooze',
  'ochtendadem', 'bedhoofd', 'kussensloop', 'dekbedovertrek', 'onderlaken',
  'klamboe', 'luchtbed', 'slaapzak', 'veldbed', 'hangmat',
  'strijkplank', 'wasknijper', 'droogmolen', 'vlekkenstift', 'wasverzachter',
  'stoomstrijkijzer', 'naaimachine', 'knoopje', 'ritssluiting', 'veter',
  'onderlegger', 'placemat', 'kaarsvet', 'theelichtje', 'asbak',
  'kurkentrekker', 'flessenopener', 'maatbeker', 'trechter', 'rietje',
  'cocktailprikker', 'ijsemmer', 'wijnkoeler', 'bierglas', 'shotglas',
  'tapkraan', 'bierfust', 'kratje', 'flesopener', 'limoenschijf',
  'pindaschaaltje', 'bitterballenschaal', 'fonduevork', 'gourmetset', 'barbecuetang',
  'aanmaakblokje', 'houtskool', 'vuurkorf', 'tuinstoel', 'hangmatpaal',
  'schommelbank', 'vogelhuisje', 'kattenluik', 'hondenmand', 'krabmast',
  'goudvissenkom', 'hamsterrad', 'vogelkooi', 'terrarium', 'aquariumpomp',
  'strandlaken', 'parasol', 'windscherm', 'bodyboard', 'zwembandjes',
  'duikplank', 'zwemvliezen', 'snorkel', 'zwembrilletje', 'reddingsboei',
  'opblaasbank', 'luchtmatras', 'zonnehoed', 'klapstoeltje', 'koelbox',
  'thermoskan', 'broodtrommel', 'lunchzak', 'drinkbus', 'picknickmand',
  'muggenspray', 'zonnebrandfactor', 'aftersun', 'pleisterrol', 'zwachtel',
  'mitella', 'rolstoel', 'rollator', 'loopgips', 'elleboogkruk',
  'spiegeltje', 'haarlak', 'krultang', 'haarband', 'scheiding',
  'pluizenroller', 'kledinghoes', 'schoenspanner', 'inlegzool', 'schoenpoets',
  'regenpak', 'poncho', 'rubberlaars', 'sneeuwketting', 'ijskrabber',
  'autoruitenwisser', 'dakkoffer', 'aanhanger', 'spanband', 'autokrik',
  'reservewiel', 'startkabel', 'jerrycan', 'pechdriehoek', 'veiligheidshesje',
  'parkeerschijf', 'wielklem', 'bonnetje', 'kassabon', 'kortingsbon',
  'spaarkaart', 'zegeltje', 'loterijbriefje', 'krasloten', 'muntautomaat',
  'pinautomaat', 'bankpas', 'portemonnee', 'kleingeld', 'briefje van vijftig',
  'kluisje', 'hangslot', 'cijferslot', 'sleutelhanger', 'reservesleutel',
  'deurmat', 'deurbel', 'brievenbus', 'kijkgaatje', 'veiligheidsketting',
  'rookmelder', 'blusdeken', 'brandblusser', 'stofzuigerzak', 'dweilemmer',
  'wc-eend', 'ontstopper', 'gootsteenzeefje', 'vaatwastablet', 'afwasteiltje',
]
