/**
 * De categorieën voor Bom Doorgeven.
 *
 * Je noemt er één uit en geeft door; wie hem vasthoudt als hij knalt drinkt.
 * Een categorie is dus alleen goed als je er onder druk snel iets uit kunt
 * halen. Te smal en de bom knalt bij de tweede speler, en dat is geen spel.
 *
 * DE TOON MOCHT STEVIGER. Er stonden dingen in als "soorten kaas" en "vogels",
 * en daar wordt een tafel van achttien niet warm van. De meeste categorieën
 * gaan nu over uitgaan, daten en wat er in een studentenhuis gebeurt — daar
 * heeft iedereen antwoorden op én je hoort meteen wie er te veel weet.
 *
 * De onschuldige zitten er nog tussen als adempauze; een potje dat alleen maar
 * over seks gaat wordt op zijn eigen manier ook saai.
 */
export const BOM_CATEGORIEEN: string[] = [
  'smoesjes om eerder weg te gaan',
  'redenen om iemand te ghosten',
  'plekken om te zoenen',
  'dingen die je niet aan je ouders vertelt',
  'slechte openingszinnen',
  'bijnamen voor dronken zijn',
  'dingen die je kwijtraakt op een festival',
  'redenen waarom een date mislukt',
  'dingen die je verstopt als er visite komt',
  'dingen waar je spijt van krijgt na vier biertjes',
  'dingen die stinken in een studentenhuis',
  'redenen om je ex te appen',
  'dingen die je doet om er nuchter uit te zien',
  'plekken waar je niet gezien wil worden',
  'dingen die een relatie om zeep helpen',
  'redenen om te laat te komen',
  'dingen die op een kamer liggen na een feest',
  'manieren om iemand af te wijzen',
  'dingen die je alleen doet als niemand kijkt',
  'redenen om iemand te blokkeren',
  'dingen die je meeneemt naar een festival',
  'tekenen dat iemand verliefd is',
  'dingen die je zegt als je betrapt wordt',
  'plekken waar het misging op vakantie',
  'dingen die niemand hardop toegeeft',
  'redenen om midden in de nacht te appen',
  'dingen die je op je telefoon verbergt',
  'manieren om onder een afspraak uit te komen',
  'dingen die je nooit meer doet na één keer',
  'redenen om vroeg naar huis te gaan',
  'dingen die iemand onaantrekkelijk maken',
  'dingen die je doet vlak voor een date',
  'biermerken',
  'cocktails',
  'snacks bij de snackbar',
  'dingen in de koelkast van een student',
  'apps op je telefoon',
  'series die iedereen gezien heeft',
  'redenen om de deur niet open te doen',
  'dingen in je broekzak na het stappen',
  'automerken',
  'Nederlandse steden',
  'dingen in deze kamer',
  'zangers of bands',
  'voetbalclubs',
  'dingen die je op een terras bestelt',
  'dingen die piepen',
  'beroepen',
  'dingen die rond zijn',
  'gereedschap',
  // ── tweede lading: breed genoeg om snel iets te kunnen roepen ──
  'dingen die je zegt vlak voor je iets stoms doet',
  'plekken waar je niet wil dat je ouders je zien',
  'redenen om een date af te zeggen',
  'dingen die je hoort door een dunne muur',
  'manieren om van iemand af te komen op een feest',
  'dingen die je van je huisgenoot leent',
  'plekken waar mensen hun telefoon verstoppen',
  'redenen om de politie te bellen',
  'dingen die kapotgaan op een huisfeest',
  'manieren om dronken thuis te komen',
  'dingen die je nooit meer terugvindt',
  'redenen om te blozen',
  'dingen die in een slaapkamerkast horen te blijven',
  'manieren om iemand het bed in te praten',
  'plekken waar je kunt zoenen zonder gezien te worden',
  'dingen die je zegt als je niet wil zoenen',
  'redenen waarom iemand niet terugappt',
  'dingen die je op je telefoon wist',
  'plekken waar je dronken in slaap valt',
  'dingen die je eet om vier uur in de nacht',
  'redenen om een kater te overleven',
  'dingen die naar bier ruiken',
  'manieren om een biertje te openen',
  'drankspellen',
  'redenen om een ronde te geven',
  'dingen die je zegt tegen een uitsmijter',
  'plekken waar een festival naar ruikt',
  'dingen die in een festivaltent liggen',
  'manieren om zonder kaartje binnen te komen',
  'redenen om vroeg weg te gaan bij je schoonouders',
  'dingen die je verzwijgt op een sollicitatie',
  'plekken waar je niet naakt wil zijn',
  'dingen die kriebelen',
  'manieren om een zuigzoen te verbergen',
  'dingen die een dokter niet grappig vindt',
  'redenen voor een spoedafspraak',
  'dingen die je aan niemand vertelt',
  'plekken waar je spijt van krijgt',
  'dingen die je om half vijf stuurt',
  'redenen om iemand uit een groepsapp te zetten',
  'dingen die op een zolderkamer gebeuren',
  'manieren om een feest te verpesten',
  'dingen die je in de wasmachine vindt',
  'plekken waar je iemand tegenkomt die je liever niet zag',
  'dingen die je niet wil horen van je huisgenoot',
  // ── onschuldiger, als adempauze ──
  'dingen die je meeneemt naar het strand',
  'merken sportschoenen',
  'dingen in een gereedschapskist',
  'soorten weer',
  'dingen die vliegen',
  // ── derde lading ──
  'dingen die je in een kroeg vindt',
  'manieren om een feest te beginnen',
  'dingen die je zegt als je binnenkomt',
  'redenen om een ronde te weigeren',
  'dingen die je kwijtraakt in een taxi',
  'plekken waar je kunt slapen als het laat is',
  'dingen die je doet tegen een kater',
  'manieren om iemand wakker te maken',
  'dingen die je in een slaapkamer hoort te verstoppen',
  'redenen om een telefoon af te pakken',
  'dingen die je zegt tegen een ex',
  'manieren om een gesprek te beginnen op een date',
  'dingen die een date verpesten',
  'plekken waar je niet op date gaat',
  'dingen die je doet om te flirten',
  'manieren om iemand duidelijk te maken dat je hem leuk vindt',
  'dingen die je nooit op een profiel zet',
  'redenen waarom iemand niet terugzoent',
  'dingen die je zegt na een slechte zoen',
  'manieren om een relatie te verpesten',
  'dingen die je vergeeft en dingen niet',
  'plekken waar paren ruzie maken',
  'dingen die in een groepsapp niet horen',
  'redenen om een screenshot te maken',
  'dingen die je op je telefoon zou wissen',
  'manieren om een leugen te verbergen',
  'dingen die je aan je moeder vertelt en niet aan je vrienden',
  'redenen om te liegen over waar je was',
  'dingen die je doet als je alleen thuis bent',
  'plekken waar het altijd stinkt',
  'dingen die in een wasmand horen',
  'manieren om van een vlek af te komen',
  'dingen die kapot zijn in je huis',
  'redenen om de huisbaas te bellen',
  'dingen die je leent en nooit teruggeeft',
  'manieren om geld te besparen',
  'dingen waar je spijt van hebt gekocht',
  'redenen om iets te retourneren',
  'dingen die je vindt in een jaszak',
  'plekken waar je geld verstopt',
  'dingen die je doet op een zondag',
  'manieren om een dag te verspillen',
  'redenen om een dag vrij te nemen',
  'dingen die je nooit meer doet na je twintigste',
  'manieren om er jonger uit te zien',
  // ── onschuldig ──
  'dingen in een koelkast',
  'soorten brood',
  'dingen met wielen',
  'dingen die je kunt opblazen',
  'soorten muziek',
]
