/**
 * Categorieën voor Bom Doorgeven.
 *
 * Ze moeten diep genoeg zijn dat de bom een paar rondjes kan maken, maar niet
 * zo makkelijk dat er nooit iemand hapert. Twintig tot dertig antwoorden per
 * categorie is de zoete plek.
 */
export const BOM_CATEGORIEEN: string[] = [
  'biermerken',
  'automerken',
  'landen in Europa',
  'Nederlandse steden',
  'dingen in de koelkast',
  'dieren met vier poten',
  'voetbalclubs',
  'dingen die je meeneemt op vakantie',
  'beroepen',
  'lichaamsdelen',
  'dingen in deze kamer',
  'zangers of bands',
  'sporten',
  'pizzabelegs',
  'snacks bij de snackbar',
  'dingen die piepen',
  'kledingmerken',
  'apps op je telefoon',
  'dingen die drijven',
  'cocktails',
  'films die je gezien hebt',
  'series op Netflix',
  'schoolvakken',
  'dingen in je broekzak',
  'jongensnamen',
  'meisjesnamen',
  'dingen die je koud eet',
  'supermarkten',
  'dingen met een schroefdop',
  'redenen om te laat te komen',
  'bordspellen',
  'games',
  'gereedschap',
  'dingen die stinken',
  'groenten',
  'soorten kaas',
  'vogels',
  'dingen op een festival',
  'muziekinstrumenten',
  'dingen die je niet aan je ouders vertelt',
  'plekken om te zoenen',
  'bijnamen voor dronken zijn',
  'dingen in een ziekenhuis',
  'iets wat je op een terras bestelt',
  'dingen die rond zijn',
  'wintersporten',
  'dingen op een verjaardag',
  'huisdieren',
  'dingen die je kunt breken',
  'dingen in een sportschool',
]
