/**
 * De categorieën voor Bom Doorgeven.
 *
 * Je noemt er één uit en geeft door; wie hem vasthoudt als hij knalt drinkt.
 * Een categorie is dus alleen goed als je er onder druk snel iets uit kunt
 * halen. Te smal en de bom knalt bij de tweede speler, en dat is geen spel.
 *
 * DE TOON MOCHT STEVIGER. Er stonden dingen in als "soorten kaas" en "vogels",
 * en daar wordt een tafel van achttien niet warm van. De meeste categorieën
 * gaan nu over uitgaan, daten en wat er in een studentenhuis gebeurt — daar
 * heeft iedereen antwoorden op én je hoort meteen wie er te veel weet.
 *
 * De onschuldige zitten er nog tussen als adempauze; een potje dat alleen maar
 * over seks gaat wordt op zijn eigen manier ook saai.
 */
export const BOM_CATEGORIEEN: string[] = [
  'smoesjes om eerder weg te gaan',
  'redenen om iemand te ghosten',
  'plekken om te zoenen',
  'dingen die je niet aan je ouders vertelt',
  'slechte openingszinnen',
  'bijnamen voor dronken zijn',
  'dingen die je kwijtraakt op een festival',
  'redenen waarom een date mislukt',
  'dingen die je verstopt als er visite komt',
  'dingen waar je spijt van krijgt na vier biertjes',
  'dingen die stinken in een studentenhuis',
  'redenen om je ex te appen',
  'dingen die je doet om er nuchter uit te zien',
  'plekken waar je niet gezien wil worden',
  'dingen die een relatie om zeep helpen',
  'redenen om te laat te komen',
  'dingen die op een kamer liggen na een feest',
  'manieren om iemand af te wijzen',
  'dingen die je alleen doet als niemand kijkt',
  'redenen om iemand te blokkeren',
  'dingen die je meeneemt naar een festival',
  'tekenen dat iemand verliefd is',
  'dingen die je zegt als je betrapt wordt',
  'plekken waar het misging op vakantie',
  'dingen die niemand hardop toegeeft',
  'redenen om midden in de nacht te appen',
  'dingen die je op je telefoon verbergt',
  'manieren om onder een afspraak uit te komen',
  'dingen die je nooit meer doet na één keer',
  'redenen om vroeg naar huis te gaan',
  'dingen die iemand onaantrekkelijk maken',
  'dingen die je doet vlak voor een date',
  'biermerken',
  'cocktails',
  'snacks bij de snackbar',
  'dingen in de koelkast van een student',
  'apps op je telefoon',
  'series die iedereen gezien heeft',
  'redenen om de deur niet open te doen',
  'dingen in je broekzak na het stappen',
  'automerken',
  'Nederlandse steden',
  'dingen in deze kamer',
  'zangers of bands',
  'voetbalclubs',
  'dingen die je op een terras bestelt',
  'dingen die piepen',
  'beroepen',
  'dingen die rond zijn',
  'gereedschap',
  // ── tweede lading: breed genoeg om snel iets te kunnen roepen ──
  'dingen die je zegt vlak voor je iets stoms doet',
  'plekken waar je niet wil dat je ouders je zien',
  'redenen om een date af te zeggen',
  'dingen die je hoort door een dunne muur',
  'manieren om van iemand af te komen op een feest',
  'dingen die je van je huisgenoot leent',
  'plekken waar mensen hun telefoon verstoppen',
  'redenen om de politie te bellen',
  'dingen die kapotgaan op een huisfeest',
  'manieren om dronken thuis te komen',
  'dingen die je nooit meer terugvindt',
  'redenen om te blozen',
  'dingen die in een slaapkamerkast horen te blijven',
  'manieren om iemand het bed in te praten',
  'plekken waar je kunt zoenen zonder gezien te worden',
  'dingen die je zegt als je niet wil zoenen',
  'redenen waarom iemand niet terugappt',
  'dingen die je op je telefoon wist',
  'plekken waar je dronken in slaap valt',
  'dingen die je eet om vier uur in de nacht',
  'redenen om een kater te overleven',
  'dingen die naar bier ruiken',
  'manieren om een biertje te openen',
  'drankspellen',
  'redenen om een ronde te geven',
  'dingen die je zegt tegen een uitsmijter',
  'plekken waar een festival naar ruikt',
  'dingen die in een festivaltent liggen',
  'manieren om zonder kaartje binnen te komen',
  'redenen om vroeg weg te gaan bij je schoonouders',
  'dingen die je verzwijgt op een sollicitatie',
  'plekken waar je niet naakt wil zijn',
  'dingen die kriebelen',
  'manieren om een zuigzoen te verbergen',
  'dingen die een dokter niet grappig vindt',
  'redenen voor een spoedafspraak',
  'dingen die je aan niemand vertelt',
  'plekken waar je spijt van krijgt',
  'dingen die je om half vijf stuurt',
  'redenen om iemand uit een groepsapp te zetten',
  'dingen die op een zolderkamer gebeuren',
  'manieren om een feest te verpesten',
  'dingen die je in de wasmachine vindt',
  'plekken waar je iemand tegenkomt die je liever niet zag',
  'dingen die je niet wil horen van je huisgenoot',
  // ── onschuldiger, als adempauze ──
  'dingen die je meeneemt naar het strand',
  'merken sportschoenen',
  'dingen in een gereedschapskist',
  'soorten weer',
  'dingen die vliegen',
]
