/**
 * De inhoud van Slecht Antwoord.
 *
 * Zelf geschreven; de kaartjes van het bekende spel zijn beschermd. Dat is
 * geen verlies, want dat spel is Amerikaans en de helft van de grappen landt
 * hier niet. Dit is geschreven voor een Nederlandse vriendengroep.
 *
 * DE TOON IS GROF, EN DAT HOORT ZO. Dit spel werkt alleen als de kaarten
 * durven. Nette kaarten leveren nette rondes op en dan is het binnen vijf
 * minuten saai. Er zit dus lichaamshumor in, seks, en dingen die je aan tafel
 * niet hardop zou zeggen — dat is het punt.
 *
 * Waar het níét over gaat, en waar ik ook niets over schrijf: groepen mensen
 * naar beneden halen om wie ze zijn, iets met kinderen, of iets waar iemand
 * niet mee ingestemd zou hebben. Dat is niet grof maar naar, en daar lacht een
 * tafel niet om — die valt er stil van.
 *
 * Wat een goed antwoord wél doet:
 *
 * · Het is concreet. "Iets viezigs" is nooit grappig, "de schaamhaar in de
 *   douche van mijn huisgenoot" wel. Hoe specifieker hoe beter.
 * · Het past in veel zinnen. Een kaart die maar bij één gat werkt zie je tien
 *   rondes lang in je hand zitten.
 * · Er zit afwisseling in. Een doodgewone Nederlandse kaart in een smerige zin
 *   is vaak grappiger dan nog een keer iets grofs — het contrast doet het werk.
 *
 * De zinnen hebben allemaal precies één gat, geschreven als ___.
 */

export const ZINNEN: string[] = [
  'Mijn moeder ging naar de winkel en zag daar ___.',
  'Het eerste wat ik doe als ik de loterij win is ___.',
  'Mijn ouders kwamen erachter dat ik ___.',
  '___ — daarom ben ik niet meer welkom bij de buren.',
  'Wat ik echt niet had verwacht op die eerste date: ___.',
  'Mijn zoekgeschiedenis bestaat voor de helft uit ___.',
  'De huisarts zei dat het vanzelf overgaat, maar toen kwam ___.',
  'Ik ben ontslagen wegens ___.',
  'Het geheim van een gelukkige relatie is ___.',
  'Wat er echt gebeurde op die bruiloft: ___.',
  '___ is precies waarom ik niet meer drink.',
  'De politie trof aan: ___.',
  'Wat ik doe als niemand kijkt: ___.',
  'Ze hebben me uit de groepsapp gegooid vanwege ___.',
  '___ hoort niet thuis in een studentenhuis.',
  'Wat er in mijn koelkast staat waar ik niets van weet: ___.',
  'Mijn therapeut is vooral bezig met ___.',
  'Ik ben verliefd geworden op iemand vanwege ___.',
  'De reden dat de brandweer moest komen: ___.',
  '___ verklaart alles over mijn jeugd.',
  'De ergste manier om wakker te worden: ___.',
  'Mijn profieltekst zou moeten zijn: ___.',
  'Wat ze op mijn begrafenis gaan zeggen: ___.',
  'De vakantie ging mis toen ___.',
  'Wat ik verstop als er visite komt: ___.',
  'Mijn moeder belt altijd precies op het moment dat ik ___.',
  'Sinds ___ slaap ik niet meer goed.',
  'De taxichauffeur wilde me niet meenemen vanwege ___.',
  'Wat er in mijn kamer ligt en er niet hoort te liggen: ___.',
  'Wat je nooit moet zeggen tegen je schoonouders: ___.',
  'De echte reden dat het uitging was ___.',
  'Op festival raakte ik kwijt: ___.',
  'Mijn huisgenoot heeft een probleem met ___.',
  'Wat ik zou doen met een dag zonder gevolgen: ___.',
  'Ik ben blij dat niemand weet van ___.',
  'De sollicitatie ging goed tot ik begon over ___.',
  'Wat er echt in die pan zat: ___.',
  'Sinterklaas bracht dit jaar ___.',
  'In de trein zat iemand met ___.',
  'Op de foto van mijn eindexamenfeest staat ___.',
  'Ik werd wakker naast ___.',
  'Wat ik op mijn achttiende verjaardag gedaan heb met ___.',
  'De reden dat ik die kamer niet meer in ga: ___.',
  'Mijn eerste keer was vooral ___.',
  'Wat ik het liefst uit mijn hoofd zou wissen: ___.',
  'De zolder van mijn opa stond vol met ___.',
  'Ik heb iemand gedumpt vanwege ___.',
  'Wat er op mijn telefoon staat en nooit iemand mag zien: ___.',
  'De onhandigste plek voor ___.',
  'Mijn huisarts vroeg of ik ooit last had van ___.',
  'Wat ik ooit heb gegoogeld en direct heb gewist: ___.',
  'Het enige wat mij nog aan kan zetten: ___.',
  'Ik ben van school gestuurd om ___.',
  'De douche van mijn vorige huis zat vol ___.',
  'Wat ik hoorde door de muur van mijn buren: ___.',
  'Mijn ex stuurde me nog één keer ___.',
  'De slechtste plek om ___ tegen te komen.',
  'Ik doe alsof ik hou van ___.',
  'Op de camping word ik herkend van ___.',
  'Wat er die avond echt in mijn bed lag: ___.',
]

export const ANTWOORDEN: string[] = [
  'een oude vrouw met laaghangende tieten',
  'de lul van de buurman',
  'een onverwachte scheet tijdens het zoenen',
  'twee ballen in een veel te strakke zwembroek',
  'de schaamhaar in de douche van mijn huisgenoot',
  'een halve stijve op het slechtst mogelijke moment',
  'mijn zoekgeschiedenis van half vier \'s nachts',
  'de buren die veel te hard kreunen',
  'een condoom dat er nog in zit',
  'de geur van een studentenhuis op zondagochtend',
  'een dickpic van een nummer dat ik niet ken',
  'mijn ouders die twee uur te vroeg thuiskomen',
  'de vlekken op mijn matras',
  'iemand die klaarkomt en meteen in slaap valt',
  'een tepel die uit een jurk piept',
  'de kont van mijn wiskundeleraar',
  'sokken die rechtop kunnen staan',
  'kotsen in de tas van iemand anders',
  'een rug die haariger is dan een deurmat',
  'de scheet die niet stil bleek te zijn',
  'iemand die zijn eigen naam roept in bed',
  'een date die de zus van mijn beste vriend bleek',
  'ongesteld worden op een witte broek',
  'een pornotab die nog openstond op de tv',
  'iemand die zoent als een wasmachine',
  'een dronken man die tegen een lantaarnpaal staat te zeiken',
  'de bilspleet van de loodgieter',
  'iemand die zijn moeder appt tijdens de seks',
  'vier dagen niet gedoucht',
  'een puist op een plek waar geen puist hoort',
  'een fles die verdacht schoon was teruggezet',
  'een slippertje met de ex van mijn beste vriend',
  'een nudefoto die naar de familiegroep ging',
  'iemand die tijdens het voorspel op zijn telefoon kijkt',
  'de zweetplekken onder een overhemd van gisteren',
  'een oude man in een te kleine zwembroek',
  'de flinterdunne muren van een studentenhuis',
  'een pornoster die heet zoals mijn oma',
  'tien minuten en dat was het',
  'de onderbroek die al drie dagen dezelfde is',
  'iemand die zijn tanden niet poetst maar wel wil zoenen',
  'de wc na mijn huisgenoot',
  'een enorme zuigzoen in je nek voor een sollicitatie',
  'iemand die praat over zijn ex tijdens de seks',
  'een bed dat het hele huis wakker maakt',
  'de vieze blik van de buurvrouw om acht uur \'s ochtends',
  'een scheet in een volle lift',
  'mijn eigen adem na een avond bier en knoflooksaus',
  'iemand die zijn nagels knipt in de woonkamer',
  'een vibrator die aanging in de handbagage',
  'de haren in de afvoer',
  'iemand die het licht aan wil',
  'een pikant appje naar de verkeerde persoon',
  'de tandenborstel die niet van mij was',
  'iemand die "papa" zegt en het niet als grap bedoelt',
  'een hickey die niet weg te werken is',
  'de geur van goedkope bodyspray over oud zweet',
  'iemand die zijn hele lichaam scheert behalve zijn rug',
  'mijn ex die nog steeds mijn Netflix gebruikt',
  'een halve frikandel in mijn jaszak',
  'drie ongelezen appjes van mijn moeder',
  'een OV-fiets die ik nooit heb teruggebracht',
  'zeventig euro aan statiegeld',
  'een tattoo die scheef staat',
  'huilen in de Albert Heijn',
  'de laatste kroket uit de muur',
  'mijn hele salaris in één avond',
  'de kat van de buren',
  'een schaal bitterballen helemaal alleen',
  'de trein die precies voor mijn neus vertrekt',
  'de hond die alles doorheeft',
  'de wc van een benzinestation',
  'een screenshot dat nooit had mogen rondgaan',
  'een kater die twee dagen duurt',
  'iemand die gitaar meeneemt naar een feestje',
  'de kassière die me veel te goed kent',
  'mijn eigen kookkunsten',
  'iemand die zegt dat hij niet dronken is',
  'een barbecue in de stromende regen',
  'de laatste bus die net weg is',
  'iemand die zijn eigen grap uitlegt',
  'de tandarts die vraagt of ik wel flos',
  'een halfvolle fles advocaat uit 2019',
  'mijn oude MSN-naam',
  'de laatste pizzapunt die niemand durft te pakken',
  'iemand die stiekem mijn oplader jat',
  'een verjaardagskring met beschuit',
  'drie euro aan kleingeld en hoop',
  'de vaatwasser die niemand uitruimt',
  'iemand die "even snel" langskomt voor vier uur',
  'mijn spaarrekening van veertien euro',
  'een gesprek over de huizenmarkt',
  'de kerstborrel van het werk',
  'iemand die met blote voeten in de keuken staat',
  'een discussie over pindakaas',
  'mijn ouders die me volgen op internet',
  'een boodschappenkarretje in de gracht',
  'de rij bij de kassa die altijd langzamer is',
  'iemand die zegt dat hij morgen vroeg op moet',
  'een tosti zonder kaas',
  'mijn oude voetbalelftal',
  'de buurvrouw die alles hoort',
  'iemand die zonder kloppen binnenkomt',
  'een gesprek dat begint met "even serieus"',
  'een sportschoolabonnement uit januari',
  'mijn hele Spotify-jaaroverzicht',
  'de kamerplant die het niet overleefde',
  'iemand die alles filmt',
  'de sleutels die in de auto liggen',
  'een pak melk dat drie dagen over datum is',
  'iemand die aan tafel zijn telefoon opneemt',
  'de zomer waar we niet meer over praten',
  'een selfie die per ongeluk vooruit ging',
  'iemand die weet hoeveel ik betaald heb',
  'een uitnodiging waar ik onderuit wil',
  'mijn oude profielfoto',
  'iemand die zegt "we moeten snel weer eens"',
  'een taxi die alleen contant wil',
  'de sleutelhanger van een hotel waar ik nooit ben geweest',
  'iemand die mijn eten van mijn bord pakt',
  'iemand die na twee biertjes gaat dansen',
  'de stilte na een slechte grap',
  'een bankoverschrijving met een hele rare omschrijving',
  'iemand die tijdens de film alles uitlegt',
  'iemand die precies weet wanneer ik lieg',
  'mijn buurman met een bladblazer om acht uur',
  'iemand die zegt dat hij het al wist',
  'een lift die op elke verdieping stopt',
  'mijn eerste bijbaantje',
  'iemand die ongevraagd advies geeft over mijn leven',
  'iemand die alles doorvertelt in de groepsapp',
  'een gesprek dat eindigt met "laat maar"',
  'de laatste slok bier die te warm is',
  'een luchtbed dat langzaam leegloopt',
  'iemand die op het feest de muziek overneemt',
  'de kruimels in mijn bed',
  'een deur die de verkeerde kant op opengaat',
  'iemand die de kaas verkeerd snijdt',
  'een handdoek die nooit droog wordt',
  'de plek waar ik mijn telefoon altijd laat liggen',
  'de rekening van de dierenarts',
  'het geluid van iemand die met een rietje drinkt',
  'een raam dat niet dicht kan',
  'de laatste keer dat ik echt gerend heb',
  'iemand die zijn schoenen aanhoudt in huis',
  'mijn eigen stem op een spraakbericht',
  'de kluis op school die ik nooit heb leeggemaakt',
  'iemand die met een rugzak op in de rij staat',
  'een pinpas die het net niet doet',
  'een bord dat veel te vol geschept is',
  'de warmte van een laptop op schoot',
  'iemand die alles beter weet over voetbal',
  'een stapel post die ik niet openmaak',
  'de kramp in mijn been om vier uur \'s nachts',
  'de verkeerde tandenborstel',
  'de bezorger die belt als ik onder de douche sta',
  'een groepsfoto waar ik met mijn ogen dicht sta',
  'het moment dat de muziek uitgaat',
  'de doos pizza van eergisteren',
  'iemand die zijn eten koud eet',
  'een paraplu die meteen omklapt',
  'mijn eigen handschrift',
  'een cadeaubon die vorig jaar al verlopen is',
  'de spiegel in de paskamer',
  'een koffieapparaat dat alleen heet water geeft',
  'de doos met kabels die ik nooit weggooi',
  'iemand die mijn naam structureel verkeerd uitspreekt',
  'een schoonmaakbeurt om drie uur \'s nachts',
  'de laatste avond van de vakantie',
  'een verjaardagslied dat veel te lang duurt',
  'de fles die net niet openging',
  'mijn eigen reflectie in een donkere trein',
  'iemand die zegt dat het "gewoon eerlijk" is',
  'een bord soep dat maar heet blijft',
  'de fiets die ik nooit op slot zet',
  'een oplader zonder kabel',
  'de bank waar ik altijd op in slaap val',
]
