/**
 * De inhoud van Cards Against Humanity.
 *
 * Zelf geschreven; de kaartjes van het bekende spel zijn beschermd. Dat is
 * geen verlies, want dat spel is Amerikaans en de helft van de grappen landt
 * hier niet. Dit is geschreven voor een Nederlandse vriendengroep.
 *
 * DE TOON IS GROF, EN DAT HOORT ZO. Dit spel werkt alleen als de kaarten
 * durven. Nette kaarten leveren nette rondes op en dan is het binnen vijf
 * minuten saai. Er zit dus lichaamshumor in, seks, en dingen die je aan tafel
 * niet hardop zou zeggen — dat is het punt.
 *
 * Waar het níét over gaat, en waar ik ook niets over schrijf: groepen mensen
 * naar beneden halen om wie ze zijn, iets met kinderen, of iets waar iemand
 * niet mee ingestemd zou hebben. Dat is niet grof maar naar, en daar lacht een
 * tafel niet om — die valt er stil van.
 *
 * Wat een goed antwoord wél doet:
 *
 * · Het is concreet. "Iets viezigs" is nooit grappig, "de schaamhaar in de
 *   douche van mijn huisgenoot" wel. Hoe specifieker hoe beter.
 * · Het past in veel zinnen. Een kaart die maar bij één gat werkt zie je tien
 *   rondes lang in je hand zitten.
 * · Er zit afwisseling in. Een doodgewone Nederlandse kaart in een smerige zin
 *   is vaak grappiger dan nog een keer iets grofs — het contrast doet het werk.
 *
 * De zinnen hebben allemaal precies één gat, geschreven als ___.
 */

/**
 * De joker: geen antwoord, maar een leeg vakje.
 *
 * Wie deze kaart legt tikt zelf iets in. Dat is de beste kaart van het spel —
 * de kaarten hieronder zijn van mij, en een tafel weet altijd iets te
 * verzinnen dat beter op deze groep slaat dan wat ik kan bedenken.
 *
 * Hij wordt aan de tekst herkend en niet aan een aparte soort, zodat de rest
 * van het spel een hand gewoon als een rij tekst kan blijven behandelen.
 */
export const JOKER = '🃏 Zelf invullen'

/**
 * Hoeveel jokers er in het dek gaan.
 *
 * Weinig, en met reden: zelf invullen wint bijna altijd. Je schrijft precies
 * op wat er in díé zin past en waar déze groep om moet lachen, en daar kan een
 * kaart van mij niet tegenop. Krijgt iedereen er elk potje een, dan is het geen
 * buitenkansje meer maar de normale manier van spelen, en dan hadden de andere
 * honderdzeventig kaarten net zo goed weg gekund.
 *
 * Eén dus. Nagerekend met een potje van vier: het dek is (spelers + 1) ×
 * (hand + rondes) groot en daar gaat zo'n zeventig procent van doorheen, dus
 * één joker betekent dat er in ruim de helft van de potjes eentje boven komt --
 * bij één iemand, niet bij iedereen. Op twee kwam hij in bijna negen van de
 * tien potjes langs, en dan is het geen buitenkansje meer.
 *
 * Dat het dek meegroeit met de tafel is precies goed: bij acht spelers is het
 * dek groter, dus blijft de kans per persoon even klein.
 */
export const JOKERS = 1

/** Hoeveel tekens iemand zelf mag intikken. */
export const JOKER_MAX = 90

export const ZINNEN: string[] = [
  'Mijn moeder ging naar de winkel en zag daar ___.',
  'Het eerste wat ik doe als ik de loterij win is ___.',
  'Mijn ouders kwamen erachter dat ik ___.',
  '___ — daarom ben ik niet meer welkom bij de buren.',
  'Wat ik echt niet had verwacht op die eerste date: ___.',
  'Mijn zoekgeschiedenis bestaat voor de helft uit ___.',
  'De huisarts zei dat het vanzelf overgaat, maar toen kwam ___.',
  'Ik ben ontslagen wegens ___.',
  'Het geheim van een gelukkige relatie is ___.',
  'Wat er echt gebeurde op die bruiloft: ___.',
  '___ is precies waarom ik niet meer drink.',
  'De politie trof aan: ___.',
  'Wat ik doe als niemand kijkt: ___.',
  'Ze hebben me uit de groepsapp gegooid vanwege ___.',
  '___ hoort niet thuis in een studentenhuis.',
  'Wat er in mijn koelkast staat waar ik niets van weet: ___.',
  'Mijn therapeut is vooral bezig met ___.',
  'Ik ben verliefd geworden op iemand vanwege ___.',
  'De reden dat de brandweer moest komen: ___.',
  '___ verklaart alles over mijn jeugd.',
  'De ergste manier om wakker te worden: ___.',
  'Mijn profieltekst zou moeten zijn: ___.',
  'Wat ze op mijn begrafenis gaan zeggen: ___.',
  'De vakantie ging mis toen ___.',
  'Wat ik verstop als er visite komt: ___.',
  'Mijn moeder belt altijd precies op het moment dat ik ___.',
  'Sinds ___ slaap ik niet meer goed.',
  'De taxichauffeur wilde me niet meenemen vanwege ___.',
  'Wat er in mijn kamer ligt en er niet hoort te liggen: ___.',
  'Wat je nooit moet zeggen tegen je schoonouders: ___.',
  'De echte reden dat het uitging was ___.',
  'Op festival raakte ik kwijt: ___.',
  'Mijn huisgenoot heeft een probleem met ___.',
  'Wat ik zou doen met een dag zonder gevolgen: ___.',
  'Ik ben blij dat niemand weet van ___.',
  'De sollicitatie ging goed tot ik begon over ___.',
  'Wat er echt in die pan zat: ___.',
  'Sinterklaas bracht dit jaar ___.',
  'In de trein zat iemand met ___.',
  'Op de foto van mijn eindexamenfeest staat ___.',
  'Ik werd wakker naast ___.',
  'Wat ik op mijn achttiende verjaardag gedaan heb met ___.',
  'De reden dat ik die kamer niet meer in ga: ___.',
  'Mijn eerste keer was vooral ___.',
  'Wat ik het liefst uit mijn hoofd zou wissen: ___.',
  'De zolder van mijn opa stond vol met ___.',
  'Ik heb iemand gedumpt vanwege ___.',
  'Wat er op mijn telefoon staat en nooit iemand mag zien: ___.',
  'De onhandigste plek voor ___.',
  'Mijn huisarts vroeg of ik ooit last had van ___.',
  'Wat ik ooit heb gegoogeld en direct heb gewist: ___.',
  'Het enige wat mij nog aan kan zetten: ___.',
  'Ik ben van school gestuurd om ___.',
  'De douche van mijn vorige huis zat vol ___.',
  'Wat ik hoorde door de muur van mijn buren: ___.',
  'Mijn ex stuurde me nog één keer ___.',
  'De slechtste plek om ___ tegen te komen.',
  'Ik doe alsof ik hou van ___.',
  'Op de camping word ik herkend van ___.',
  'Wat er die avond echt in mijn bed lag: ___.',
  // ── tweede lading zinnen ──
  'Mijn huisgenoot heeft de badkamer op slot gedaan vanwege ___.',
  'De reden dat ik nooit meer bij mijn tante logeer: ___.',
  'Wat ik vond onder het bed van mijn vorige huisgenoot: ___.',
  'Op de camping staat iedereen te kijken naar ___.',
  'Mijn nieuwe hobby is ___.',
  'Het ging fout tijdens de familiebarbecue door ___.',
  'Wat ik ruik als ik de trein in stap: ___.',
  'De beveiliging heeft me eruit gezet vanwege ___.',
  'Mijn laatste relatie strandde op ___.',
  'Het eerste wat ik doe als ik onzichtbaar ben: ___.',
  'Wat er stond in de brief van de verhuurder: ___.',
  'Ik kan niet slapen door ___.',
  'Mijn ouders denken dat ik studeer, maar eigenlijk doe ik ___.',
  'Op mijn grafsteen komt te staan: ___.',
  'De grootste fout in mijn tienerjaren was ___.',
  'Wat ik tegenkwam in de kleedkamer van de sportschool: ___.',
  'De reden dat mijn wifi-naam is aangepast: ___.',
  'Wat ik hoorde tijdens de vergadering toen iemand vergat te muten: ___.',
  'Ik heb drie uur in de wachtrij gestaan voor ___.',
  'Het cadeau waar niemand op zat te wachten: ___.',
  'Mijn zoektocht naar geluk eindigde bij ___.',
  'Wat ik doe zodra iedereen slaapt: ___.',
  'De echte reden dat ik geen huisdier mag: ___.',
  'Op de eerste schooldag vertelde ik iedereen over ___.',
  'Het ergste dat je kunt aantreffen in een deelauto: ___.',
  'Mijn dokter keek bezorgd toen ik zei ___.',
  'Wat ik verstop als de schoonmaker komt: ___.',
  'De reden dat ik uit de groepsapp ben gezet: ___.',
  'Wat er gebeurde nadat ik lachgas had geprobeerd: ___.',
  'Mijn buurman klopte om drie uur aan vanwege ___.',
  'Het geheim van mijn opa bleek ___ te zijn.',
  'Wat ik in mijn tas vond na het festival: ___.',
  'Ik werd wakker met ___ in mijn hand.',
  'De therapeut noemde het ___.',
  'Wat mijn moeder vond in mijn jaszak: ___.',
  'Het foutje dat mij mijn rijbewijs kostte: ___.',
  'Ik zou alles opgeven voor ___.',
  'Mijn nieuwe tinderfoto is ___.',
  'Wat er misging tijdens de yogales: ___.',
  'De reden dat het alarm afging in de supermarkt: ___.',
  'Wat ik doe om indruk te maken op schoonouders: ___.',
  'De grootste teleurstelling van mijn vakantie was ___.',
  'Ik heb per ongeluk ___ naar mijn baas gestuurd.',
  'Wat ik hoorde door de muur van het hotel: ___.',
  'Mijn favoriete manier om een gesprek te beëindigen is ___.',
  'De reden dat wij geen huisfeest meer mogen geven: ___.',
  'Wat ik aantrof toen ik te vroeg thuiskwam: ___.',
  'De enige manier om mij uit bed te krijgen is ___.',
  'Wat ik meenam naar de eerste date: ___.',
  'In mijn nachtkastje ligt ___.',
  'De reden dat ik nooit meer meega naar een bruiloft: ___.',
  'Wat mij is overkomen in de sauna: ___.',
  'Mijn zoekgeschiedenis van gisteravond bestond uit ___.',
  'Het ergste geluid dat je kunt horen in een tent: ___.',
  'Wat ik doe als ik alleen thuis ben: ___.',
  'De reden dat ik mijn camera uitzette: ___.',
  'Wat er in de koelkast van mijn huisgenoot staat: ___.',
  'Mijn ex herinnert zich vooral ___.',
  'Wat ik heb geleerd van mijn eerste keer: ___.',
  'De reden dat de politie werd gebeld: ___.',
  // ── derde lading zinnen ──
  'Het ergste dat je kunt zeggen tijdens de seks: ___.',
  'Mijn huisgenoot heeft een briefje opgehangen over ___.',
  'Wat ik heb geleerd van mijn laatste one-night stand: ___.',
  'De reden dat ik niet meer welkom ben in die kroeg: ___.',
  'Wat er gebeurde toen mijn ouders op vakantie waren: ___.',
  'Mijn beste smoes is ___.',
  'Het eerste wat ik zoek op een nieuwe telefoon: ___.',
  'Wat ik tegenkwam op het profiel van mijn ex: ___.',
  'De grootste rode vlag op een date is ___.',
  'Wat ik doe als de wifi uitvalt: ___.',
  'Mijn slaapkamer ruikt naar ___.',
  'Wat ik verstop voor mijn huisgenoot: ___.',
  'Op de badkamerspiegel staat ___ geschreven.',
  'De reden dat ik mijn tandarts niet meer in de ogen kan kijken: ___.',
  'Wat ik meeneem naar een festival en nooit terugvind: ___.',
  'Het laatste wat ik me van gisteravond herinner is ___.',
  'De reden dat er geen foto\'s zijn van dat weekend: ___.',
  'Wat mijn huisgenoot vond in de wasmachine: ___.',
  'Het geluid dat ik hoorde door de slaapkamermuur: ___.',
  'Wat er op de bodycam van die bezorger staat: ___.',
  'Mijn date vroeg wat mijn type was en ik zei ___.',
  'De reden dat ik geblokkeerd ben: ___.',
  'Wat er in de groepsapp werd gezet om vier uur: ___.',
  'Het ergste cadeau van een ex: ___.',
  'Wat ik heb gevonden onder het bed van mijn huisgenoot: ___.',
  'De reden dat de buren de politie belden: ___.',
  'Wat ik tegen de uitsmijter zei: ___.',
  'Mijn laatste zoekopdracht was ___.',
  'Wat er niet in mijn vakantiefoto\'s terechtkwam: ___.',
  'De echte reden dat ik niet meer drink op zondag: ___.',
  'Wat ik hoorde in de kleedkamer: ___.',
  'Het ergste dat je kunt vinden in een deelauto: ___.',
  'Mijn therapeut werd stil toen ik begon over ___.',
  'Wat ik doe als niemand mij kan zien: ___.',
  'De reden dat mijn ex nog steeds mijn moeder appt: ___.',
  'Wat er gebeurde op die ene bruiloft: ___.',
  'Het ergste moment om te niezen: ___.',
  'Wat ik aantrof in de logeerkamer: ___.',
  'De reden dat die foto van internet is gehaald: ___.',
  'Wat mijn huisarts opschreef in mijn dossier: ___.',
  'Het ergste om te horen van je huisgenoot: ___.',
  'Wat er stond op de factuur die ik niet kon uitleggen: ___.',
  'Mijn grootste talent is ___.',
  'Wat ik doe om een gesprek te stoppen: ___.',
  'De reden dat ik nooit meer meega naar de sauna: ___.',
  'Wat er misging tijdens de vrijgezellenavond: ___.',
  'Het ergste dat je kunt aantreffen in een hotelbed: ___.',
  'Mijn nieuwe wifi-naam is ___.',
  'Wat ik heb gedaan voor twee euro: ___.',
  'De reden dat ik niet meer mag oppassen: ___.',
  'Wat mijn vriendengroep nog steeds niet weet: ___.',
  'Het eerste wat ik doe na een breuk: ___.',
  'Wat ik meeneem naar de wc: ___.',
  'De reden dat ik dat T-shirt heb weggegooid: ___.',
  'Wat er gebeurde achter de festivaltent: ___.',
  'Het ergste om te zien bij daglicht: ___.',
  'Wat ik heb verzwegen tijdens het sollicitatiegesprek: ___.',
  'De reden dat mijn huisgenoot op de bank slaapt: ___.',
  'Wat mijn oma zei toen ze het hoorde: ___.',
  'Het laatste bericht dat ik verstuurde was ___.',
  // ── vierde lading zinnen ──
  'Mijn huisgenoot belde de huisbaas over ___.',
  'Wat ik vond toen ik de bank omhoog tilde: ___.',
  'De reden dat ik mijn borg niet terugkrijg: ___.',
  'Wat er op de muur van de wc stond: ___.',
  'Mijn moeder vroeg wat ___ betekende.',
  'De reden dat ik niet meer in die supermarkt kom: ___.',
  'Wat ik meeneem als het huis in brand staat: ___.',
  'Het ergste om te vinden in je eigen jaszak: ___.',
  'Mijn nieuwe goede voornemen is ___.',
  'Wat ik doe als ik een uur te vroeg ben: ___.',
  'De reden dat het bedrijfsuitje vroeg eindigde: ___.',
  'Wat mijn collega op kantoor achterliet: ___.',
  'Het ergste om te ontvangen van je baas: ___.',
  'Wat ik verzwijg op mijn cv: ___.',
  'De reden dat ik ben overgeplaatst: ___.',
  'Wat er in de kantinemicrowave is gebeurd: ___.',
  'Het ergste geluid tijdens een vergadering: ___.',
  'Wat ik hoor als ik mijn oordopjes uitdoe in de trein: ___.',
  'De reden dat die coupé werd afgesloten: ___.',
  'Wat de conducteur niet wilde zien: ___.',
  'Het ergste om naast je te hebben in het vliegtuig: ___.',
  'Wat er in mijn koffer zat bij de douane: ___.',
  'De reden dat mijn paspoort apart werd bekeken: ___.',
  'Wat ik heb gekocht op vakantie en nooit gebruikt: ___.',
  'Het ergste souvenir: ___.',
  'Wat er in het hotelbed lag: ___.',
  'De reden dat de receptie belde: ___.',
  'Wat ik meenam uit die hotelkamer: ___.',
  'Het ergste om te zien op de camping: ___.',
  'Wat er uit de tent naast ons kwam: ___.',
  'De reden dat de campingbaas langskwam: ___.',
  'Wat ik heb gedaan met het laatste douchemuntje: ___.',
  'Het ergste om mee te maken in een zwembad: ___.',
  'Wat er in de sauna gebeurde: ___.',
  'De reden dat ik uit het zwembad moest: ___.',
  'Wat ik achterliet in het kleedhokje: ___.',
  'Het ergste om te horen bij de huisarts: ___.',
  'Wat er op mijn uitslag stond: ___.',
  'De reden dat ik met spoed moest komen: ___.',
  'Wat de apotheker luid voorlas: ___.',
  'Het ergste om te vergeten voor een date: ___.',
  'Wat mijn date vroeg en ik niet wist: ___.',
  'De reden dat er geen tweede date kwam: ___.',
  'Wat ik zei toen zij vroeg wat ik zocht: ___.',
  'Het ergste om te horen de ochtend erna: ___.',
  'Wat er op het nachtkastje lag: ___.',
  'De reden dat ik mijn ex nog één keer appte: ___.',
  'Wat mijn ex terugstuurde: ___.',
  'Het ergste cadeau voor een bruiloft: ___.',
  'Wat er in de speech voorbijkwam: ___.',
  'De reden dat de bruid huilde: ___.',
  'Wat er met het bruidsboeket is gebeurd: ___.',
  'Het ergste om te doen op een begrafenis: ___.',
  'Wat mijn oma zei op de verjaardag: ___.',
  'De reden dat mijn tante niet meer komt: ___.',
  'Wat er in het sinterklaasgedicht stond: ___.',
  'Het ergste om te krijgen met kerst: ___.',
  'Wat er met de kerstboom is gebeurd: ___.',
  'De reden dat oud en nieuw vroeg eindigde: ___.',
  'Wat er met het vuurwerk misging: ___.',
  'Het ergste om tegen te komen om zes uur in de ochtend: ___.',
  'Wat ik doe als de bus niet komt: ___.',
  'De reden dat ik moest lopen: ___.',
  'Wat ik heb beloofd en nooit gedaan: ___.',
  'Het ergste om te horen van je huisgenoot door de muur: ___.',
  'Wat ik heb gedaan toen de stroom uitviel: ___.',
  'De reden dat de politie werd gebeld door de buren: ___.',
  'Wat ik op de buurtapp heb gezet: ___.',
  'Het ergste om te zijn op een feest: ___.',
  'Wat ik doe als ik niemand ken: ___.',
  'De reden dat ik ben weggestuurd: ___.',
  'Wat er met mijn jas is gebeurd: ___.',
  'Het ergste om te verliezen op een festival: ___.',
  'Wat er in mijn tent lag toen ik terugkwam: ___.',
  'De reden dat ik het hoofdpodium heb gemist: ___.',
  'Wat ik heb geruild voor een biertje: ___.',
  'Het ergste om mee te maken in een tent: ___.',
  'Wat mijn vrienden nog steeds navertellen: ___.',
  'De reden dat ik een nieuwe bijnaam heb: ___.',
  'Wat er op mijn verjaardagskaart stond: ___.',
]

export const ANTWOORDEN: string[] = [
  'een oude vrouw met laaghangende tieten',
  'de lul van de buurman',
  'een onverwachte scheet tijdens het zoenen',
  'twee ballen in een veel te strakke zwembroek',
  'de schaamhaar in de douche van mijn huisgenoot',
  'een halve stijve op het slechtst mogelijke moment',
  'mijn zoekgeschiedenis van half vier \'s nachts',
  'de buren die veel te hard kreunen',
  'een condoom dat er nog in zit',
  'de geur van een studentenhuis op zondagochtend',
  'een dickpic van een nummer dat ik niet ken',
  'mijn ouders die twee uur te vroeg thuiskomen',
  'de vlekken op mijn matras',
  'iemand die klaarkomt en meteen in slaap valt',
  'een tepel die uit een jurk piept',
  'de kont van mijn wiskundeleraar',
  'sokken die rechtop kunnen staan',
  'kotsen in de tas van iemand anders',
  'een rug die haariger is dan een deurmat',
  'de scheet die niet stil bleek te zijn',
  'iemand die zijn eigen naam roept in bed',
  'een date die de zus van mijn beste vriend bleek',
  'ongesteld worden op een witte broek',
  'een pornotab die nog openstond op de tv',
  'iemand die zoent als een wasmachine',
  'een dronken man die tegen een lantaarnpaal staat te zeiken',
  'de bilspleet van de loodgieter',
  'iemand die zijn moeder appt tijdens de seks',
  'vier dagen niet gedoucht',
  'een puist op een plek waar geen puist hoort',
  'een fles die verdacht schoon was teruggezet',
  'een slippertje met de ex van mijn beste vriend',
  'een nudefoto die naar de familiegroep ging',
  'iemand die tijdens het voorspel op zijn telefoon kijkt',
  'de zweetplekken onder een overhemd van gisteren',
  'een oude man in een te kleine zwembroek',
  'de flinterdunne muren van een studentenhuis',
  'een pornoster die heet zoals mijn oma',
  'tien minuten en dat was het',
  'de onderbroek die al drie dagen dezelfde is',
  'iemand die zijn tanden niet poetst maar wel wil zoenen',
  'de wc na mijn huisgenoot',
  'een enorme zuigzoen in je nek voor een sollicitatie',
  'iemand die praat over zijn ex tijdens de seks',
  'een bed dat het hele huis wakker maakt',
  'de vieze blik van de buurvrouw om acht uur \'s ochtends',
  'een scheet in een volle lift',
  'mijn eigen adem na een avond bier en knoflooksaus',
  'iemand die zijn nagels knipt in de woonkamer',
  'een vibrator die aanging in de handbagage',
  'de haren in de afvoer',
  'iemand die het licht aan wil',
  'een pikant appje naar de verkeerde persoon',
  'de tandenborstel die niet van mij was',
  'iemand die "papa" zegt en het niet als grap bedoelt',
  'een hickey die niet weg te werken is',
  'de geur van goedkope bodyspray over oud zweet',
  'iemand die zijn hele lichaam scheert behalve zijn rug',
  'mijn ex die nog steeds mijn Netflix gebruikt',
  'een halve frikandel in mijn jaszak',
  'drie ongelezen appjes van mijn moeder',
  'een OV-fiets die ik nooit heb teruggebracht',
  'zeventig euro aan statiegeld',
  'een tattoo die scheef staat',
  'huilen in de Albert Heijn',
  'de laatste kroket uit de muur',
  'mijn hele salaris in één avond',
  'de kat van de buren',
  'een schaal bitterballen helemaal alleen',
  'de trein die precies voor mijn neus vertrekt',
  'de hond die alles doorheeft',
  'de wc van een benzinestation',
  'een screenshot dat nooit had mogen rondgaan',
  'een kater die twee dagen duurt',
  'iemand die gitaar meeneemt naar een feestje',
  'de kassière die me veel te goed kent',
  'mijn eigen kookkunsten',
  'iemand die zegt dat hij niet dronken is',
  'een barbecue in de stromende regen',
  'de laatste bus die net weg is',
  'iemand die zijn eigen grap uitlegt',
  'de tandarts die vraagt of ik wel flos',
  'een halfvolle fles advocaat uit 2019',
  'mijn oude MSN-naam',
  'de laatste pizzapunt die niemand durft te pakken',
  'iemand die stiekem mijn oplader jat',
  'een verjaardagskring met beschuit',
  'drie euro aan kleingeld en hoop',
  'de vaatwasser die niemand uitruimt',
  'iemand die "even snel" langskomt voor vier uur',
  'mijn spaarrekening van veertien euro',
  'een gesprek over de huizenmarkt',
  'de kerstborrel van het werk',
  'iemand die met blote voeten in de keuken staat',
  'een discussie over pindakaas',
  'mijn ouders die me volgen op internet',
  'een boodschappenkarretje in de gracht',
  'de rij bij de kassa die altijd langzamer is',
  'iemand die zegt dat hij morgen vroeg op moet',
  'een tosti zonder kaas',
  'mijn oude voetbalelftal',
  'de buurvrouw die alles hoort',
  'iemand die zonder kloppen binnenkomt',
  'een gesprek dat begint met "even serieus"',
  'een sportschoolabonnement uit januari',
  'mijn hele Spotify-jaaroverzicht',
  'de kamerplant die het niet overleefde',
  'iemand die alles filmt',
  'de sleutels die in de auto liggen',
  'een pak melk dat drie dagen over datum is',
  'iemand die aan tafel zijn telefoon opneemt',
  'de zomer waar we niet meer over praten',
  'een selfie die per ongeluk vooruit ging',
  'iemand die weet hoeveel ik betaald heb',
  'een uitnodiging waar ik onderuit wil',
  'mijn oude profielfoto',
  'iemand die zegt "we moeten snel weer eens"',
  'een taxi die alleen contant wil',
  'de sleutelhanger van een hotel waar ik nooit ben geweest',
  'iemand die mijn eten van mijn bord pakt',
  'iemand die na twee biertjes gaat dansen',
  'de stilte na een slechte grap',
  'een bankoverschrijving met een hele rare omschrijving',
  'iemand die tijdens de film alles uitlegt',
  'iemand die precies weet wanneer ik lieg',
  'mijn buurman met een bladblazer om acht uur',
  'iemand die zegt dat hij het al wist',
  'een lift die op elke verdieping stopt',
  'mijn eerste bijbaantje',
  'iemand die ongevraagd advies geeft over mijn leven',
  'iemand die alles doorvertelt in de groepsapp',
  'een gesprek dat eindigt met "laat maar"',
  'de laatste slok bier die te warm is',
  'een luchtbed dat langzaam leegloopt',
  'iemand die op het feest de muziek overneemt',
  'de kruimels in mijn bed',
  'een deur die de verkeerde kant op opengaat',
  'iemand die de kaas verkeerd snijdt',
  'een handdoek die nooit droog wordt',
  'de plek waar ik mijn telefoon altijd laat liggen',
  'de rekening van de dierenarts',
  'het geluid van iemand die met een rietje drinkt',
  'een raam dat niet dicht kan',
  'de laatste keer dat ik echt gerend heb',
  'iemand die zijn schoenen aanhoudt in huis',
  'mijn eigen stem op een spraakbericht',
  'de kluis op school die ik nooit heb leeggemaakt',
  'iemand die met een rugzak op in de rij staat',
  'een pinpas die het net niet doet',
  'een bord dat veel te vol geschept is',
  'de warmte van een laptop op schoot',
  'iemand die alles beter weet over voetbal',
  'een stapel post die ik niet openmaak',
  'de kramp in mijn been om vier uur \'s nachts',
  'de verkeerde tandenborstel',
  'de bezorger die belt als ik onder de douche sta',
  'een groepsfoto waar ik met mijn ogen dicht sta',
  'het moment dat de muziek uitgaat',
  'de doos pizza van eergisteren',
  'iemand die zijn eten koud eet',
  'een paraplu die meteen omklapt',
  'mijn eigen handschrift',
  'een cadeaubon die vorig jaar al verlopen is',
  'de spiegel in de paskamer',
  'een koffieapparaat dat alleen heet water geeft',
  'de doos met kabels die ik nooit weggooi',
  'iemand die mijn naam structureel verkeerd uitspreekt',
  'een schoonmaakbeurt om drie uur \'s nachts',
  'de laatste avond van de vakantie',
  'een verjaardagslied dat veel te lang duurt',
  'de fles die net niet openging',
  'mijn eigen reflectie in een donkere trein',
  'iemand die zegt dat het "gewoon eerlijk" is',
  'een bord soep dat maar heet blijft',
  'de fiets die ik nooit op slot zet',
  'een oplader zonder kabel',
  'de bank waar ik altijd op in slaap val',
  // ── tweede lading antwoorden ──
  //
  // Bewust in drie smaken door elkaar. Een lijst die alleen maar grof is wordt
  // voorspelbaar: als élke kaart over een geslachtsdeel gaat, is geen enkele
  // kaart nog een verrassing. Het contrast tussen een smerige zin en een
  // doodgewone Nederlandse kaart is waar de tafel het hardst om lacht.
  'de scheet die harder was dan verwacht',
  'een kruimel van gisteren tussen de billen',
  'de vieze vaatdoek die naar dode muis ruikt',
  'twee nagels die veel te lang zijn',
  'de haren in de afvoer van de douche',
  'een washand die niemand van zichzelf durft te noemen',
  'de tandenborstel die al drie jaar meegaat',
  'kotsen in de bosjes bij de buren',
  'een puist die niet meer te negeren is',
  'de geur van iemand die net heeft gesport',
  'de onderbroek die binnenstebuiten weer aan is gegaan',
  'de sok die aan het plafond plakt',
  'een luchtje dat de lift niet uit gaat',
  'de schimmel tussen de tegels',
  'een verkeerd getimede boer',
  'de zweetvlekken in de vorm van Australië',
  'de haren die opeens uit een oor komen',
  'een navelpluis van formaat',
  'de teennagel die achterbleef in het bad',
  'de restjes in de gootsteen na het afwassen',
  'een tepel die door een wit shirt heen kijkt',
  'de stijve die op precies het verkeerde moment kwam',
  'een zuigzoen ter grootte van een bierviltje',
  'de tanga die in de wasmachine van de buren belandde',
  'de bh die aan de lamp hing',
  'de nudes die per ongeluk naar de familiegroep gingen',
  'het geluid van een bed dat het niet meer trekt',
  'een condoom in de wc dat niet wegspoelt',
  'de zoenpartij in de fietsenstalling',
  'de morning-afterpil om acht uur bij de apotheek',
  'iemand die je naam vergeet tijdens de seks',
  'twee minuten en toen was het klaar',
  'de buurman die alles hoort en er niets van zegt',
  'een date die zijn moeder meenam',
  'de ex die nog steeds elke story bekijkt',
  'iemand die klaarkomt en meteen gaat koken',
  'de schaamharen op het zeepje',
  'een dickpic bij daglicht',
  'de seksspeeltjes die de hond gevonden heeft',
  'iemand die het hele huis wakker kreunt',
  'de tweede telefoon in het handschoenenkastje',
  'de handboeien zonder sleuteltje',
  'een driehoeksverhouding met de huisgenoot',
  'de vrijgezellenavond waar niemand over praat',
  'een zuigzoen die drie weken bleef zitten',
  'het matras dat mee moest naar de stort',
  'de bekentenis om vier uur in de ochtend',
  'de kat die erbij zat te kijken',
  'een blinde date met je eigen buurvrouw',
  'de wc-deur die niet op slot bleek te zitten',
  'de frikandel speciaal om half vijf',
  'een kapsalon met extra knoflook',
  'de bak drop die niemand meeneemt',
  'de laatste bitterbal die op tafel blijft liggen',
  'een statiegeldbon van twee euro tien',
  'de blauwe container die te vroeg buiten staat',
  'de buurtapp met een klacht over hondenpoep',
  'een tuinkabouter met te veel zelfvertrouwen',
  'de sinterklaas die duidelijk de buurman is',
  'de oliebol van drie dagen oud',
  'een partytent die wegwaait',
  'de klapstoel die het begeeft',
  'het springkussen op een barbecue voor volwassenen',
  'de kerstborrel met de directeur op de dansvloer',
  'een carnavalspak in juli',
  'de fiets die al twee jaar op het station staat',
  'een ov-chipkaart met nog negentig cent erop',
  'de slippers met sokken eronder',
  'de partytent die naar bier ruikt',
  'de opblaaskrokodil die de vijver op drijft',
  'een megafoon om zes uur in de ochtend',
  'de pruik die niet meer recht zit',
  'een confettikanon binnenshuis',
  'de rookmachine die het brandalarm activeert',
  'de tondeuse in verkeerde handen',
  'het lijmpistool en een heel slecht idee',
  'een waterpistool gevuld met iets anders',
  'de ladder die tegen het verkeerde raam stond',
  'de bodycam van iemand die te veel filmt',
  'de beveiligingsbeelden van de parkeergarage',
  'de nekbrace die niemand kan uitleggen',
  'krukken na een weddenschap van twee euro',
  'een parkeerboete op een trouwdag',
  'de pinpas die is ingeslikt door de automaat',
  'de sleutelbos in de gracht',
  'een taxichauffeur die weigert te rijden',
  'de nachtbus vol met mensen die naar hun werk gaan',
  'de uitsmijter die je naam kent',
  'iemand die lachgas doet en daarna filosofeert',
  'de kroegtijger die als laatste vertrekt',
  'een shotje dat naar benzine smaakt',
  'de tequila waar het altijd misgaat',
  'een blackout van drie uur',
  'de danspaal in een huiskamer',
  'de afterparty bij iemand die je niet kent',
  'de garderobebon die kwijt is',
  'een energiedrank op een lege maag',
  'het bierviltje met iemands nummer erop',
  'de braakemmer die doorgegeven wordt',
  'de kater die drie dagen duurt',
  'de groepsapp die om zeven uur ontploft',
  'de gedeelde locatie die stilstaat op een vreemd adres',
  'een ongelezen bericht van drie dagen oud',
  'de profielfoto van acht jaar geleden',
  'iemand die zijn zoekgeschiedenis vergeet te wissen',
  'de spraakmemo van elf minuten',
  'een screenshot dat naar de verkeerde ging',
  'de wifi-naam van de buren',
  'een bezorger die te veel gezien heeft',
  'de schoonmoeder die onaangekondigd langskomt',
  'de stiefvader die het gesprek aangaat',
  'een wijkagent met te veel interesse',
  'de tattoo met een spelfout',
  'de spiegel in de kleedkamer met slecht licht',
  'iemand die de sauna verkeerd begrepen heeft',
  'het naaktstrand met bekenden erop',
  'de zonnebrand in de vorm van een hand',
  'een invalidentoilet dat verkeerd gebruikt wordt',
  'de logeerkamer met veel te dunne muren',
  'iemand die de badkuip als bed gebruikt',
  'de dakgoot waar je niet meer uit komt',
  'het portiek waar iedereen doorheen loopt',
  'de draaideur die klem zit',
  'een kelder waar niemand heen wil',
  'de fietsenstalling om drie uur in de nacht',
  'de caravan van iemands opa',
  'de festivaltent die instort',
  'een wachtkamer met te veel oogcontact',
  'de achterbank met kruimels en spijt',
  'het politiebureau als eindpunt van de avond',
  // ── derde lading: harder, en bewust explicieter ──
  //
  // De tafel is achttien en heeft de hele lijst al gezien, dus de rem mag er
  // verder af. Wat hier niet in staat blijft hetzelfde: niets met kinderen,
  // niets waar iemand niet mee ingestemd zou hebben, en geen groepen mensen
  // naar beneden halen om wie ze zijn. Dat is niet grof maar naar.
  'een onverwachte vinger',
  'de derde keer op één nacht',
  'twee mensen die niet meer uit elkaar te halen zijn',
  'een lul die kleiner is dan beloofd',
  'de buurvrouw die vraagt of het zachter kan',
  'klaarkomen in precies vier seconden',
  'een orgasme dat duidelijk nep was',
  'de kreun die door het hele portiek ging',
  'iemand die midden in de daad zijn naam verkeerd zegt',
  'een bed dat tegen de muur ramt',
  'de tandarts die vraagt waar die plek vandaan komt',
  'een piercing op een onverwachte plek',
  'de knoop in een condoom die niet lukte',
  'iemand die tijdens de seks de scorebordapp opent',
  'een dildo in de vaatwasser',
  'de vibrator die aanging in de handbagage',
  'een glijmiddel dat verward werd met tandpasta',
  'drie mensen en één matras',
  'een vriendin die precies vertelt hoe het was',
  'de ochtend waarop niemand wist wie wie was',
  'een scheet op het slechtst denkbare moment',
  'iemand die klaarkomt en begint te huilen',
  'de harde schijf met een map die niemand mag openen',
  'de zoekgeschiedenis die alles verklaart',
  'een paar sokken die aan bleef tijdens de seks',
  'de hond die op het bed sprong halverwege',
  'iemand die zijn moeder belt met de deur open',
  'een driehoeksverhouding in hetzelfde studentenhuis',
  'de huisgenoot die alles woordelijk heeft gehoord',
  'twee exen op dezelfde kroegavond',
  'de vrijpartij die op de bodycam van een bezorger staat',
  'een naaktfoto met het hele huis erop',
  'de spiegel die precies de verkeerde kant op stond',
  'iemand die vergeet dat de camera nog aan is',
  'een gedeelde locatie die alles verraadt',
  'de tweede telefoon onder het matras',
  'een appje van de ex van je beste vriend',
  'iemand die erbij blijft dat het niets betekende',
  'de ene keer dronken die niet meetelt',
  'een huilende man in een nachtclub',
  'iemand die midden in de seks in slaap valt',
  'de lul van de uitsmijter',
  'een stripper die een bekende bleek te zijn',
  'de zuigzoen die drie weken bleef',
  'iemand die zijn eigen billen filmt voor een like',
  'de schaamharen die in de zeep zitten',
  'een onderbroek die niet van iemand hier is',
  'de bh aan de buitenlamp',
  'een string in de wasmachine van de buren',
  'de boxershort op het dak van de garage',
  'iemand die naakt in de keuken staat te koken',
  'de verrassing waar niemand om vroeg',
  'een rollenspel dat te vroeg eindigde',
  'handboeien waar het sleuteltje bij ontbrak',
  'de knuffel die ergens anders voor gebruikt werd',
  'een opblaaspop met een naam',
  'de kreet die de brandweer op het verkeerde been zette',
  'twee mensen in een invalidentoilet',
  'de kleedkamer van de sportschool om half acht',
  'een sauna met je schoonvader erin',
  'de wc van de trein tussen twee stations',
  'een festivaltent zonder enig geheim',
  'de achterbank van een deelauto',
  'iemand die in de fietsenstalling betrapt werd',
  'de zolderkamer met een heel dunne vloer',
  'een logeerbed dat niet meer te verbergen was',
  'de badkuip als slechtste idee ooit',
  'een portiek met een bewegingssensor',
  'de nachtbus met twee mensen te veel',
  'iemand die zijn kleren niet meer kon vinden',
  'de zonnebrand met een duidelijke afdruk erin',
  'een hele vakantie met één condoom',
  'de morning-afterpil in de supermarkt',
  'een zwangerschapstest in de wc van het cafe',
  'de blaasontsteking die alles verraadde',
  'iemand die het aan de huisarts moest uitleggen',
  'de uitslag die niemand verwachtte',
  'een gesprek met de huisarts over een vreemd plekje',
  'de spoedafspraak op maandagochtend',
  'iemand die googelt of het normaal is',
  'de vraag of het nog wel hoort te prikken',
  'een afspraak bij de soa-poli',
  'de fles wijn die als enige getuige overbleef',
  'iemand die het hele verhaal aan zijn moeder vertelt',
  'de beste vriend die alles al wist',
  'een groepsapp met een screenshot te veel',
  'de ex die nog steeds de wifi gebruikt',
  'iemand die zijn tinderprofiel niet weghaalt',
  'de match die je tante bleek te zijn',
  'een date die zijn eigen foto niet was',
  'de man die zei dat hij single was',
  'iemand die zijn ring in zijn zak doet',
  'de trouwfoto op de achtergrond van een videogesprek',
  'een bruiloft waar twee mensen te veel elkaar kenden',
  'de bruidegom die de verkeerde naam zei',
  'een vrijgezellenfeest dat te ver ging',
  'de stripper op de verkeerde verdieping',
  'iemand die op een bruiloft met de ober verdwijnt',
  'de tante die zich uitstekend vermaakte',
  'een opa met te veel verhalen',
  'de schoonmoeder die het bed opmaakte en iets vond',
  // ── vierde lading: vies, dom en doodgewoon door elkaar ──
  'een boer die naar frikandel ruikt',
  'de poep van iemand anders in de wc',
  'een wc zonder papier en zonder uitweg',
  'de voetlucht in een tweepersoonstent',
  'iemand die drie dagen dezelfde sokken aanheeft',
  'de oksels van de spinningdocent',
  'een niesbui vol met meer dan lucht',
  'de haren in de afvoer die niemand opruimt',
  'iemand die in de wasbak plast',
  'de luier van een hond',
  'een kotszak die het net niet haalde',
  'de braakemmer die doorgegeven werd',
  'iemand die kotst in de capuchon van een vriend',
  'de kauwgom onder de tafel van het cafe',
  'een tandenborstel die van twee mensen blijkt te zijn',
  'de washand van de huisgenoot',
  'iemand die met de handdoek van de buren afdroogt',
  'de scheerbeurt die halverwege strandde',
  'een rugwax zonder waarschuwing',
  'de teennagel in het voeteneinde',
  'iemand die zijn navel uitpeutert aan tafel',
  'de korst die er niet af mocht',
  'een pukkel met publiek',
  'de knie die de verkeerde kant op stond',
  'iemand die van de trap valt en blijft lachen',
  'de nekbrace als souvenir',
  'een hechting boven het oog',
  'de eerste hulp om vijf uur in de ochtend',
  'iemand die zijn tand terugvindt in de kebab',
  'de weddenschap die twee euro opleverde',
  'een gebroken tafel en vier verdachten',
  'de deur die uit zijn hengsels ging',
  'iemand die door een glazen deur loopt',
  'de trampoline en een slecht plan',
  'een springkussen met een barbecue ernaast',
  'de schutting van de buren als brandhout',
  'iemand die een boom in klimt om indruk te maken',
  'de fontein waar iemand in sprong',
  'een supermarktkarretje op de snelweg',
  'de verkeerspaal die het niet overleefde',
  'iemand die het hek verwarde met zijn voordeur',
  'de politie die vraagt of dit uw fiets is',
  'een boete voor iets wat niet bestaat',
  'de uitsmijter die je bij je voornaam kent',
  'iemand die onderhandelt met een uitsmijter',
  'de taxi die halverwege stopt',
  'een nacht op het bureau en geen verhaal',
  'de wijkagent die langskomt voor de derde keer',
  'iemand die zijn eigen huis probeert in te breken',
  'de sleutels in de gracht',
  'een telefoon in de wc-pot',
  'de laptop en een halve liter bier',
  'iemand die op zijn eigen bril gaat zitten',
  'de pinpas die in de automaat bleef',
  'een bankrekening van negentien cent',
  'de rekening die door iemand anders betaald werd',
  'iemand die nooit tikt en altijd meedrinkt',
  'de ronde die nooit gegeven werd',
  'een statiegeldbon als cadeau',
  'de kapsalon met te veel knoflook',
  'een shoarma om half zes in de ochtend',
  'de patat die in het zand viel',
  'iemand die ongevraagd van je bord eet',
  'de laatste bitterbal en twee handen',
  'een frikandel speciaal zonder speciaal',
  'de pizza die koud bezorgd werd',
  'iemand die ananas op pizza verdedigt',
  'de stamppot van de schoonmoeder',
  'een bak drop die niemand aanraakt',
  'de oliebol van vorige week',
  'iemand die zijn eigen bier niet terugvindt',
  'de fles die verdacht leeg was',
  'een kratje dat in twee uur leeg ging',
  'de wijn uit een pak',
  'iemand die bier mengt met energiedrank',
  'de shot die naar schoonmaakmiddel smaakte',
  'een drankspel dat niemand begreep',
  'de regels die ter plekke verzonnen werden',
  'iemand die vals speelt bij een drankspel',
  'de telefoon die rondgaat met iemands verhaal erop',
  'een spraakbericht van elf minuten',
  'de groepsapp die om zeven uur ontplofte',
  'iemand die alles filmt en niets onthoudt',
  'de story die te laat verwijderd werd',
  'een screenshot bij de verkeerde persoon',
  'iemand die de verkeerde groep antwoordt',
  'de autocorrectie die het erger maakte',
  'een voicememo die per ongeluk doorging',
  'de microfoon die aan bleef in de vergadering',
  'iemand die vergeet dat hij in beeld is',
  'het wachtwoord dat op de koelkast hangt',
  'een printer die alles uitprint wat je niet wil',
  'iemand die inlogt op het verkeerde account',
  'de zoekbalk die suggesties doet voor publiek',
  'een tatoeage met een spelfout',
  'de pruik die afzakte op de dansvloer',
  'iemand in een carnavalspak in juli',
  'de zonnebril binnen in de kroeg',
  'een shirt dat drie maten te klein is',
  'iemand die danst alsof hij betaald wordt',
  'de gitaar die tevoorschijn kwam na middernacht',
  'een karaokeversie die niemand overleefde',
  'de buurman die om drie uur meezong',
  'iemand die het hele huis wakker maakt met een megafoon',
  'de rookmachine die de brandweer liet komen',
  'een confettikanon in een kleine kamer',
  'de opblaaskrokodil in de gracht',
  'iemand die het springkussen laat leeglopen',
  'de tuinslang als wapen',
  'een waterpistool met iets anders erin',
  'de tondeuse zonder opzetstuk',
  'iemand die midden in de nacht de keuken verbouwt',
  'de ladder tegen het verkeerde raam',
  'een partytent die wegwaait met tafel en al',
  // ── vijfde lading antwoorden ──
  'een huisgenoot die nooit afwast',
  'de schimmel achter de koelkast',
  'een kraan die blijft lekken',
  'de boiler die het opgaf in januari',
  'een afvoer vol met andermans haren',
  'de koelkast met één bruine banaan',
  'een pan die drie dagen bleef staan',
  'de vaatwasser die nooit wordt uitgeruimd',
  'een vuilniszak die niemand buiten zet',
  'de container die te vol is',
  'een huisbaas die nooit opneemt',
  'de borg die je nooit terugziet',
  'een huurcontract vol kleine lettertjes',
  'de verhuisdoos die drie jaar dicht bleef',
  'een kamer van negen vierkante meter',
  'de buren die om zeven uur stofzuigen',
  'een bovenbuurman met houten vloeren',
  'de hond van de benedenbuur',
  'een buurtapp vol klachten',
  'de bezorger die gewoon binnenkomt',
  'een pakketje bij de verkeerde deur',
  'de retourzending die nooit is aangekomen',
  'een abonnement dat niet op te zeggen is',
  'de rekening van twee jaar geleden',
  'een incasso op het slechtste moment',
  'de pinpas die geweigerd wordt',
  'een bankrekening met negentien cent',
  'de tikkie die nooit betaald wordt',
  'een vriend die altijd zijn portemonnee vergeet',
  'de rekening die gedeeld moet worden door zeven',
  'een treinvertraging van vijfenveertig minuten',
  'de conducteur die precies nu langskomt',
  'een volle coupé met één raam open',
  'de medepassagier die hardop belt',
  'een kinderwagen in het gangpad',
  'de nachttrein met één wakkere man',
  'een taxi die contant wil',
  'de deelscooter zonder accu',
  'een lekke band op de ergste plek',
  'de fiets zonder zadel',
  'een wielklem op maandagochtend',
  'de parkeerboete onder de ruitenwisser',
  'een flitser die net afgaat',
  'de blaastest om half vier',
  'een rijexamen dat tien minuten duurde',
  'de instructeur die alleen zuchtte',
  'een tentamen waar niemand voor leerde',
  'de herkansing die ook niet lukte',
  'een presentatie zonder sheets',
  'de beamer die niet wil',
  'een printer met een storing',
  'de microfoon die aan bleef',
  'een videogesprek met een slechte verbinding',
  'de collega die vergeet te muten',
  'een mail naar iedereen in plaats van één',
  'de reply-all van dertig berichten',
  'een wachtwoord dat je al drie keer hebt gewijzigd',
  'de phishingmail waar iemand op klikte',
  'een inbox met duizend ongelezen berichten',
  'de agenda-uitnodiging voor zeven uur',
  'een bedrijfsuitje met verplichte spelletjes',
  'de kerstborrel met de directeur',
  'een kerstpakket vol kruidenmixen',
  'de teambuilding in de regen',
  'een loonstrookje dat lager is dan beloofd',
  'de ziekmelding op de dag na een feest',
  'een sollicitatiebrief die naar de verkeerde ging',
  'de proeftijd die niet werd verlengd',
  'een assessment met rollenspel',
  'de stagebegeleider die niets deed',
  'een werkgroep met één werkende persoon',
  'de deadline van vanmiddag',
  'een plagiaatcontrole met een slechte uitslag',
  'de kantine met lauwe soep',
  'een microwave die naar vis ruikt',
  'de koffieautomaat die alleen water geeft',
  'een vergadering die een mail had kunnen zijn',
  'de notulen die niemand leest',
  'een organigram met te veel vakjes',
  'de functioneringsgesprekken in december',
  'een enquête over werkgeluk',
  'de verplichte cursus van drie uur',
  'een brandoefening op het drukste moment',
  'de lift die blijft steken',
  'een draaideur met een rugzak',
  'de sleutelkaart die niet werkt',
  'een beveiliger met te veel tijd',
  'de bezoekerspas met de verkeerde naam',
  'een parkeerplek voor de directie',
  'de laadpas die niet werkt',
  'een jerrycan in de kofferbak',
  'de startkabel die je nooit nodig had',
  'een pechdriehoek op de vluchtstrook',
  'de wegenwacht die twee uur duurt',
  'een aanhanger die scheef staat',
  'de dakkoffer die open ging',
  'een spanband die knapte',
  'de kruiwagen vol tuinafval',
  'een heg die te hoog is voor de buren',
  'de schutting die omwaaide',
  'een vuurkorf op het verkeerde moment',
  'de barbecue in de regen',
  'een partytent van vijftien euro',
  'de klapstoel die het begaf',
  'een springkussen zonder pomp',
  'de hogedrukspuit en een slecht idee',
  'een tuinslang in de voordeur',
  'de grasmachine om acht uur op zondag',
  'een bloempot die van het balkon viel',
  'de kat van de buren in je tuin',
  'een vogelhuisje zonder vogels',
  'de krabmast die nooit gebruikt wordt',
  'een hamster die ontsnapt is',
  'de goudvis die het niet heeft gehaald',
  'een aquariumpomp die zoemt',
  'de hond die alles opeet',
  'een kattenbak die niemand verschoont',
  'de dierenarts met een rekening',
  'een halsband met een belletje',
  'de dierenwinkel met een advies te veel',
  'een weegschaal die niets goeds zegt',
  'de spierpijn van gisteren',
  'een personal trainer met te veel energie',
  'de proteineshake die naar krijt smaakt',
  'een loopband op de hoogste stand',
  'de spinningles met harde muziek',
  'een sportschoolabonnement van januari',
  'de kleedkamer met één bankje',
  'een natte handdoek op de bank',
  'de sauna met te veel oogcontact',
  'een massage die te hard was',
  'de pedicure met slecht nieuws',
  'een gezichtsmasker voor de camera',
  'de tandarts die zucht',
  'een beugel op je vijfentwintigste',
  'de verdoving die niet werkte',
  'een wortelkanaal op vrijdagmiddag',
  'de wachtkamer met oude tijdschriften',
  'een bloedprik door een stagiair',
  'de verwijsbrief die kwijt is',
  'een recept dat niet te lezen is',
  'de apotheek die hardop voorleest',
  'een pleister die niet blijft zitten',
  'de gipsarm met tekeningen erop',
  'een mitella die je niet nodig hebt',
  'de krukken die je kwijt bent',
  'een rolstoel op een drempel',
  'de thermometer met een hoog getal',
  'een neusspray-verslaving',
  'de hoestdrank met te veel effect',
  'een vitaminepil die niets doet',
  'de slaappil die te laat werkte',
  'een wekker die drie keer afgaat',
  'de snooze van veertig minuten',
  'een slaapmasker dat afzakt',
  'de oordopjes die je kwijt bent',
  'een bedhoofd van zes uur slapen',
  'de ochtendadem van een vreemde',
  'een kussensloop die naar haarlak ruikt',
  'de dekbedovertrek die nooit verschoond wordt',
  'een luchtbed dat leegloopt',
  'de slaapzak met een rits die vastzit',
  'een veldbed dat doorzakt',
  'de hangmat die losschoot',
  'een strijkplank als nachtkastje',
  'de wasknijper die je nodig had',
  'een droogmolen vol onderbroeken',
  'de vlekkenstift die niets uithaalde',
  'een wasverzachter die te veel ruikt',
  'de naaimachine die niemand kan gebruiken',
  'een knoopje dat je nooit vastzet',
  'de veter die steeds losgaat',
  'een inlegzool uit een andere schoen',
  'de schoenpoets uit 2011',
  'een regenpak dat niemand aan wil',
  'de poncho op een festival',
  'een rubberlaars vol water',
  'de ijskrabber die in de auto ligt',
  'een sneeuwketting zonder sneeuw',
  'de kortingsbon die verlopen is',
  'een spaarkaart met één zegel',
  'de krasloten die niets opleveren',
  'een loterijbriefje in de wasmachine',
  'de kassabon van anderhalve meter',
  'een muntautomaat die alles inslikt',
  'de kluisjes zonder sleutel',
  'een cijferslot waarvan je de code kwijt bent',
  'de reservesleutel onder de mat',
  'een deurbel met camera',
  'de brievenbus vol reclame',
  'een kijkgaatje waar iemand voor staat',
  'de veiligheidsketting die niets tegenhoudt',
  'een rookmelder met een lege batterij',
  'de blusdeken die nooit gebruikt is',
  'een brandblusser die verlopen is',
  'de stofzuigerzak die vol is',
  'een dweilemmer midden in de gang',
  'de wc-eend die achter de pot staat',
  'een ontstopper die het niet haalt',
  'de vaatwastablet zonder vaatwasser',
  'een afwasteiltje als badkuip',
]
