/**
 * De inhoud van Cards Against Humanity.
 *
 * Zelf geschreven; de kaartjes van het bekende spel zijn beschermd. Dat is
 * geen verlies, want dat spel is Amerikaans en de helft van de grappen landt
 * hier niet. Dit is geschreven voor een Nederlandse vriendengroep.
 *
 * DE TOON IS GROF, EN DAT HOORT ZO. Dit spel werkt alleen als de kaarten
 * durven. Nette kaarten leveren nette rondes op en dan is het binnen vijf
 * minuten saai. Er zit dus lichaamshumor in, seks, en dingen die je aan tafel
 * niet hardop zou zeggen — dat is het punt.
 *
 * Waar het níét over gaat, en waar ik ook niets over schrijf: groepen mensen
 * naar beneden halen om wie ze zijn, iets met kinderen, of iets waar iemand
 * niet mee ingestemd zou hebben. Dat is niet grof maar naar, en daar lacht een
 * tafel niet om — die valt er stil van.
 *
 * Wat een goed antwoord wél doet:
 *
 * · Het is concreet. "Iets viezigs" is nooit grappig, "de schaamhaar in de
 *   douche van mijn huisgenoot" wel. Hoe specifieker hoe beter.
 * · Het past in veel zinnen. Een kaart die maar bij één gat werkt zie je tien
 *   rondes lang in je hand zitten.
 * · Er zit afwisseling in. Een doodgewone Nederlandse kaart in een smerige zin
 *   is vaak grappiger dan nog een keer iets grofs — het contrast doet het werk.
 *
 * De zinnen hebben allemaal precies één gat, geschreven als ___.
 */

/**
 * De joker: geen antwoord, maar een leeg vakje.
 *
 * Wie deze kaart legt tikt zelf iets in. Dat is de beste kaart van het spel —
 * de kaarten hieronder zijn van mij, en een tafel weet altijd iets te
 * verzinnen dat beter op deze groep slaat dan wat ik kan bedenken.
 *
 * Hij wordt aan de tekst herkend en niet aan een aparte soort, zodat de rest
 * van het spel een hand gewoon als een rij tekst kan blijven behandelen.
 */
export const JOKER = '🃏 Zelf invullen'

/**
 * Hoeveel jokers er in het dek gaan.
 *
 * Weinig, en met reden: zelf invullen wint bijna altijd. Je schrijft precies
 * op wat er in díé zin past en waar déze groep om moet lachen, en daar kan een
 * kaart van mij niet tegenop. Krijgt iedereen er elk potje een, dan is het geen
 * buitenkansje meer maar de normale manier van spelen, en dan hadden de andere
 * honderdzeventig kaarten net zo goed weg gekund.
 *
 * Eén dus. Nagerekend met een potje van vier: het dek is (spelers + 1) ×
 * (hand + rondes) groot en daar gaat zo'n zeventig procent van doorheen, dus
 * één joker betekent dat er in ruim de helft van de potjes eentje boven komt --
 * bij één iemand, niet bij iedereen. Op twee kwam hij in bijna negen van de
 * tien potjes langs, en dan is het geen buitenkansje meer.
 *
 * Dat het dek meegroeit met de tafel is precies goed: bij acht spelers is het
 * dek groter, dus blijft de kans per persoon even klein.
 */
export const JOKERS = 1

/** Hoeveel tekens iemand zelf mag intikken. */
export const JOKER_MAX = 90

export const ZINNEN: string[] = [
  'Mijn moeder ging naar de winkel en zag daar ___.',
  'Het eerste wat ik doe als ik de loterij win is ___.',
  'Mijn ouders kwamen erachter dat ik ___.',
  '___ — daarom ben ik niet meer welkom bij de buren.',
  'Wat ik echt niet had verwacht op die eerste date: ___.',
  'Mijn zoekgeschiedenis bestaat voor de helft uit ___.',
  'De huisarts zei dat het vanzelf overgaat, maar toen kwam ___.',
  'Ik ben ontslagen wegens ___.',
  'Het geheim van een gelukkige relatie is ___.',
  'Wat er echt gebeurde op die bruiloft: ___.',
  '___ is precies waarom ik niet meer drink.',
  'De politie trof aan: ___.',
  'Wat ik doe als niemand kijkt: ___.',
  'Ze hebben me uit de groepsapp gegooid vanwege ___.',
  '___ hoort niet thuis in een studentenhuis.',
  'Wat er in mijn koelkast staat waar ik niets van weet: ___.',
  'Mijn therapeut is vooral bezig met ___.',
  'Ik ben verliefd geworden op iemand vanwege ___.',
  'De reden dat de brandweer moest komen: ___.',
  '___ verklaart alles over mijn jeugd.',
  'De ergste manier om wakker te worden: ___.',
  'Mijn profieltekst zou moeten zijn: ___.',
  'Wat ze op mijn begrafenis gaan zeggen: ___.',
  'De vakantie ging mis toen ___.',
  'Wat ik verstop als er visite komt: ___.',
  'Mijn moeder belt altijd precies op het moment dat ik ___.',
  'Sinds ___ slaap ik niet meer goed.',
  'De taxichauffeur wilde me niet meenemen vanwege ___.',
  'Wat er in mijn kamer ligt en er niet hoort te liggen: ___.',
  'Wat je nooit moet zeggen tegen je schoonouders: ___.',
  'De echte reden dat het uitging was ___.',
  'Op festival raakte ik kwijt: ___.',
  'Mijn huisgenoot heeft een probleem met ___.',
  'Wat ik zou doen met een dag zonder gevolgen: ___.',
  'Ik ben blij dat niemand weet van ___.',
  'De sollicitatie ging goed tot ik begon over ___.',
  'Wat er echt in die pan zat: ___.',
  'Sinterklaas bracht dit jaar ___.',
  'In de trein zat iemand met ___.',
  'Op de foto van mijn eindexamenfeest staat ___.',
  'Ik werd wakker naast ___.',
  'Wat ik op mijn achttiende verjaardag gedaan heb met ___.',
  'De reden dat ik die kamer niet meer in ga: ___.',
  'Mijn eerste keer was vooral ___.',
  'Wat ik het liefst uit mijn hoofd zou wissen: ___.',
  'De zolder van mijn opa stond vol met ___.',
  'Ik heb iemand gedumpt vanwege ___.',
  'Wat er op mijn telefoon staat en nooit iemand mag zien: ___.',
  'De onhandigste plek voor ___.',
  'Mijn huisarts vroeg of ik ooit last had van ___.',
  'Wat ik ooit heb gegoogeld en direct heb gewist: ___.',
  'Het enige wat mij nog aan kan zetten: ___.',
  'Ik ben van school gestuurd om ___.',
  'De douche van mijn vorige huis zat vol ___.',
  'Wat ik hoorde door de muur van mijn buren: ___.',
  'Mijn ex stuurde me nog één keer ___.',
  'De slechtste plek om ___ tegen te komen.',
  'Ik doe alsof ik hou van ___.',
  'Op de camping word ik herkend van ___.',
  'Wat er die avond echt in mijn bed lag: ___.',
  // ── tweede lading zinnen ──
  'Mijn huisgenoot heeft de badkamer op slot gedaan vanwege ___.',
  'De reden dat ik nooit meer bij mijn tante logeer: ___.',
  'Wat ik vond onder het bed van mijn vorige huisgenoot: ___.',
  'Op de camping staat iedereen te kijken naar ___.',
  'Mijn nieuwe hobby is ___.',
  'Het ging fout tijdens de familiebarbecue door ___.',
  'Wat ik ruik als ik de trein in stap: ___.',
  'De beveiliging heeft me eruit gezet vanwege ___.',
  'Mijn laatste relatie strandde op ___.',
  'Het eerste wat ik doe als ik onzichtbaar ben: ___.',
  'Wat er stond in de brief van de verhuurder: ___.',
  'Ik kan niet slapen door ___.',
  'Mijn ouders denken dat ik studeer, maar eigenlijk doe ik ___.',
  'Op mijn grafsteen komt te staan: ___.',
  'De grootste fout in mijn tienerjaren was ___.',
  'Wat ik tegenkwam in de kleedkamer van de sportschool: ___.',
  'De reden dat mijn wifi-naam is aangepast: ___.',
  'Wat ik hoorde tijdens de vergadering toen iemand vergat te muten: ___.',
  'Ik heb drie uur in de wachtrij gestaan voor ___.',
  'Het cadeau waar niemand op zat te wachten: ___.',
  'Mijn zoektocht naar geluk eindigde bij ___.',
  'Wat ik doe zodra iedereen slaapt: ___.',
  'De echte reden dat ik geen huisdier mag: ___.',
  'Op de eerste schooldag vertelde ik iedereen over ___.',
  'Het ergste dat je kunt aantreffen in een deelauto: ___.',
  'Mijn dokter keek bezorgd toen ik zei ___.',
  'Wat ik verstop als de schoonmaker komt: ___.',
  'De reden dat ik uit de groepsapp ben gezet: ___.',
  'Wat er gebeurde nadat ik lachgas had geprobeerd: ___.',
  'Mijn buurman klopte om drie uur aan vanwege ___.',
  'Het geheim van mijn opa bleek ___ te zijn.',
  'Wat ik in mijn tas vond na het festival: ___.',
  'Ik werd wakker met ___ in mijn hand.',
  'De therapeut noemde het ___.',
  'Wat mijn moeder vond in mijn jaszak: ___.',
  'Het foutje dat mij mijn rijbewijs kostte: ___.',
  'Ik zou alles opgeven voor ___.',
  'Mijn nieuwe tinderfoto is ___.',
  'Wat er misging tijdens de yogales: ___.',
  'De reden dat het alarm afging in de supermarkt: ___.',
  'Wat ik doe om indruk te maken op schoonouders: ___.',
  'De grootste teleurstelling van mijn vakantie was ___.',
  'Ik heb per ongeluk ___ naar mijn baas gestuurd.',
  'Wat ik hoorde door de muur van het hotel: ___.',
  'Mijn favoriete manier om een gesprek te beëindigen is ___.',
  'De reden dat wij geen huisfeest meer mogen geven: ___.',
  'Wat ik aantrof toen ik te vroeg thuiskwam: ___.',
  'De enige manier om mij uit bed te krijgen is ___.',
  'Wat ik meenam naar de eerste date: ___.',
  'In mijn nachtkastje ligt ___.',
  'De reden dat ik nooit meer meega naar een bruiloft: ___.',
  'Wat mij is overkomen in de sauna: ___.',
  'Mijn zoekgeschiedenis van gisteravond bestond uit ___.',
  'Het ergste geluid dat je kunt horen in een tent: ___.',
  'Wat ik doe als ik alleen thuis ben: ___.',
  'De reden dat ik mijn camera uitzette: ___.',
  'Wat er in de koelkast van mijn huisgenoot staat: ___.',
  'Mijn ex herinnert zich vooral ___.',
  'Wat ik heb geleerd van mijn eerste keer: ___.',
  'De reden dat de politie werd gebeld: ___.',
]

export const ANTWOORDEN: string[] = [
  'een oude vrouw met laaghangende tieten',
  'de lul van de buurman',
  'een onverwachte scheet tijdens het zoenen',
  'twee ballen in een veel te strakke zwembroek',
  'de schaamhaar in de douche van mijn huisgenoot',
  'een halve stijve op het slechtst mogelijke moment',
  'mijn zoekgeschiedenis van half vier \'s nachts',
  'de buren die veel te hard kreunen',
  'een condoom dat er nog in zit',
  'de geur van een studentenhuis op zondagochtend',
  'een dickpic van een nummer dat ik niet ken',
  'mijn ouders die twee uur te vroeg thuiskomen',
  'de vlekken op mijn matras',
  'iemand die klaarkomt en meteen in slaap valt',
  'een tepel die uit een jurk piept',
  'de kont van mijn wiskundeleraar',
  'sokken die rechtop kunnen staan',
  'kotsen in de tas van iemand anders',
  'een rug die haariger is dan een deurmat',
  'de scheet die niet stil bleek te zijn',
  'iemand die zijn eigen naam roept in bed',
  'een date die de zus van mijn beste vriend bleek',
  'ongesteld worden op een witte broek',
  'een pornotab die nog openstond op de tv',
  'iemand die zoent als een wasmachine',
  'een dronken man die tegen een lantaarnpaal staat te zeiken',
  'de bilspleet van de loodgieter',
  'iemand die zijn moeder appt tijdens de seks',
  'vier dagen niet gedoucht',
  'een puist op een plek waar geen puist hoort',
  'een fles die verdacht schoon was teruggezet',
  'een slippertje met de ex van mijn beste vriend',
  'een nudefoto die naar de familiegroep ging',
  'iemand die tijdens het voorspel op zijn telefoon kijkt',
  'de zweetplekken onder een overhemd van gisteren',
  'een oude man in een te kleine zwembroek',
  'de flinterdunne muren van een studentenhuis',
  'een pornoster die heet zoals mijn oma',
  'tien minuten en dat was het',
  'de onderbroek die al drie dagen dezelfde is',
  'iemand die zijn tanden niet poetst maar wel wil zoenen',
  'de wc na mijn huisgenoot',
  'een enorme zuigzoen in je nek voor een sollicitatie',
  'iemand die praat over zijn ex tijdens de seks',
  'een bed dat het hele huis wakker maakt',
  'de vieze blik van de buurvrouw om acht uur \'s ochtends',
  'een scheet in een volle lift',
  'mijn eigen adem na een avond bier en knoflooksaus',
  'iemand die zijn nagels knipt in de woonkamer',
  'een vibrator die aanging in de handbagage',
  'de haren in de afvoer',
  'iemand die het licht aan wil',
  'een pikant appje naar de verkeerde persoon',
  'de tandenborstel die niet van mij was',
  'iemand die "papa" zegt en het niet als grap bedoelt',
  'een hickey die niet weg te werken is',
  'de geur van goedkope bodyspray over oud zweet',
  'iemand die zijn hele lichaam scheert behalve zijn rug',
  'mijn ex die nog steeds mijn Netflix gebruikt',
  'een halve frikandel in mijn jaszak',
  'drie ongelezen appjes van mijn moeder',
  'een OV-fiets die ik nooit heb teruggebracht',
  'zeventig euro aan statiegeld',
  'een tattoo die scheef staat',
  'huilen in de Albert Heijn',
  'de laatste kroket uit de muur',
  'mijn hele salaris in één avond',
  'de kat van de buren',
  'een schaal bitterballen helemaal alleen',
  'de trein die precies voor mijn neus vertrekt',
  'de hond die alles doorheeft',
  'de wc van een benzinestation',
  'een screenshot dat nooit had mogen rondgaan',
  'een kater die twee dagen duurt',
  'iemand die gitaar meeneemt naar een feestje',
  'de kassière die me veel te goed kent',
  'mijn eigen kookkunsten',
  'iemand die zegt dat hij niet dronken is',
  'een barbecue in de stromende regen',
  'de laatste bus die net weg is',
  'iemand die zijn eigen grap uitlegt',
  'de tandarts die vraagt of ik wel flos',
  'een halfvolle fles advocaat uit 2019',
  'mijn oude MSN-naam',
  'de laatste pizzapunt die niemand durft te pakken',
  'iemand die stiekem mijn oplader jat',
  'een verjaardagskring met beschuit',
  'drie euro aan kleingeld en hoop',
  'de vaatwasser die niemand uitruimt',
  'iemand die "even snel" langskomt voor vier uur',
  'mijn spaarrekening van veertien euro',
  'een gesprek over de huizenmarkt',
  'de kerstborrel van het werk',
  'iemand die met blote voeten in de keuken staat',
  'een discussie over pindakaas',
  'mijn ouders die me volgen op internet',
  'een boodschappenkarretje in de gracht',
  'de rij bij de kassa die altijd langzamer is',
  'iemand die zegt dat hij morgen vroeg op moet',
  'een tosti zonder kaas',
  'mijn oude voetbalelftal',
  'de buurvrouw die alles hoort',
  'iemand die zonder kloppen binnenkomt',
  'een gesprek dat begint met "even serieus"',
  'een sportschoolabonnement uit januari',
  'mijn hele Spotify-jaaroverzicht',
  'de kamerplant die het niet overleefde',
  'iemand die alles filmt',
  'de sleutels die in de auto liggen',
  'een pak melk dat drie dagen over datum is',
  'iemand die aan tafel zijn telefoon opneemt',
  'de zomer waar we niet meer over praten',
  'een selfie die per ongeluk vooruit ging',
  'iemand die weet hoeveel ik betaald heb',
  'een uitnodiging waar ik onderuit wil',
  'mijn oude profielfoto',
  'iemand die zegt "we moeten snel weer eens"',
  'een taxi die alleen contant wil',
  'de sleutelhanger van een hotel waar ik nooit ben geweest',
  'iemand die mijn eten van mijn bord pakt',
  'iemand die na twee biertjes gaat dansen',
  'de stilte na een slechte grap',
  'een bankoverschrijving met een hele rare omschrijving',
  'iemand die tijdens de film alles uitlegt',
  'iemand die precies weet wanneer ik lieg',
  'mijn buurman met een bladblazer om acht uur',
  'iemand die zegt dat hij het al wist',
  'een lift die op elke verdieping stopt',
  'mijn eerste bijbaantje',
  'iemand die ongevraagd advies geeft over mijn leven',
  'iemand die alles doorvertelt in de groepsapp',
  'een gesprek dat eindigt met "laat maar"',
  'de laatste slok bier die te warm is',
  'een luchtbed dat langzaam leegloopt',
  'iemand die op het feest de muziek overneemt',
  'de kruimels in mijn bed',
  'een deur die de verkeerde kant op opengaat',
  'iemand die de kaas verkeerd snijdt',
  'een handdoek die nooit droog wordt',
  'de plek waar ik mijn telefoon altijd laat liggen',
  'de rekening van de dierenarts',
  'het geluid van iemand die met een rietje drinkt',
  'een raam dat niet dicht kan',
  'de laatste keer dat ik echt gerend heb',
  'iemand die zijn schoenen aanhoudt in huis',
  'mijn eigen stem op een spraakbericht',
  'de kluis op school die ik nooit heb leeggemaakt',
  'iemand die met een rugzak op in de rij staat',
  'een pinpas die het net niet doet',
  'een bord dat veel te vol geschept is',
  'de warmte van een laptop op schoot',
  'iemand die alles beter weet over voetbal',
  'een stapel post die ik niet openmaak',
  'de kramp in mijn been om vier uur \'s nachts',
  'de verkeerde tandenborstel',
  'de bezorger die belt als ik onder de douche sta',
  'een groepsfoto waar ik met mijn ogen dicht sta',
  'het moment dat de muziek uitgaat',
  'de doos pizza van eergisteren',
  'iemand die zijn eten koud eet',
  'een paraplu die meteen omklapt',
  'mijn eigen handschrift',
  'een cadeaubon die vorig jaar al verlopen is',
  'de spiegel in de paskamer',
  'een koffieapparaat dat alleen heet water geeft',
  'de doos met kabels die ik nooit weggooi',
  'iemand die mijn naam structureel verkeerd uitspreekt',
  'een schoonmaakbeurt om drie uur \'s nachts',
  'de laatste avond van de vakantie',
  'een verjaardagslied dat veel te lang duurt',
  'de fles die net niet openging',
  'mijn eigen reflectie in een donkere trein',
  'iemand die zegt dat het "gewoon eerlijk" is',
  'een bord soep dat maar heet blijft',
  'de fiets die ik nooit op slot zet',
  'een oplader zonder kabel',
  'de bank waar ik altijd op in slaap val',
  // ── tweede lading antwoorden ──
  //
  // Bewust in drie smaken door elkaar. Een lijst die alleen maar grof is wordt
  // voorspelbaar: als élke kaart over een geslachtsdeel gaat, is geen enkele
  // kaart nog een verrassing. Het contrast tussen een smerige zin en een
  // doodgewone Nederlandse kaart is waar de tafel het hardst om lacht.
  'de scheet die harder was dan verwacht',
  'een kruimel van gisteren tussen de billen',
  'de vieze vaatdoek die naar dode muis ruikt',
  'twee nagels die veel te lang zijn',
  'de haren in de afvoer van de douche',
  'een washand die niemand van zichzelf durft te noemen',
  'de tandenborstel die al drie jaar meegaat',
  'kotsen in de bosjes bij de buren',
  'een puist die niet meer te negeren is',
  'de geur van iemand die net heeft gesport',
  'de onderbroek die binnenstebuiten weer aan is gegaan',
  'de sok die aan het plafond plakt',
  'een luchtje dat de lift niet uit gaat',
  'de schimmel tussen de tegels',
  'een verkeerd getimede boer',
  'de zweetvlekken in de vorm van Australië',
  'de haren die opeens uit een oor komen',
  'een navelpluis van formaat',
  'de teennagel die achterbleef in het bad',
  'de restjes in de gootsteen na het afwassen',
  'een tepel die door een wit shirt heen kijkt',
  'de stijve die op precies het verkeerde moment kwam',
  'een zuigzoen ter grootte van een bierviltje',
  'de tanga die in de wasmachine van de buren belandde',
  'de bh die aan de lamp hing',
  'de nudes die per ongeluk naar de familiegroep gingen',
  'het geluid van een bed dat het niet meer trekt',
  'een condoom in de wc dat niet wegspoelt',
  'de zoenpartij in de fietsenstalling',
  'de morning-afterpil om acht uur bij de apotheek',
  'iemand die je naam vergeet tijdens de seks',
  'twee minuten en toen was het klaar',
  'de buurman die alles hoort en er niets van zegt',
  'een date die zijn moeder meenam',
  'de ex die nog steeds elke story bekijkt',
  'iemand die klaarkomt en meteen gaat koken',
  'de schaamharen op het zeepje',
  'een dickpic bij daglicht',
  'de seksspeeltjes die de hond gevonden heeft',
  'iemand die het hele huis wakker kreunt',
  'de tweede telefoon in het handschoenenkastje',
  'de handboeien zonder sleuteltje',
  'een driehoeksverhouding met de huisgenoot',
  'de vrijgezellenavond waar niemand over praat',
  'een zuigzoen die drie weken bleef zitten',
  'het matras dat mee moest naar de stort',
  'de bekentenis om vier uur in de ochtend',
  'de kat die erbij zat te kijken',
  'een blinde date met je eigen buurvrouw',
  'de wc-deur die niet op slot bleek te zitten',
  'de frikandel speciaal om half vijf',
  'een kapsalon met extra knoflook',
  'de bak drop die niemand meeneemt',
  'de laatste bitterbal die op tafel blijft liggen',
  'een statiegeldbon van twee euro tien',
  'de blauwe container die te vroeg buiten staat',
  'de buurtapp met een klacht over hondenpoep',
  'een tuinkabouter met te veel zelfvertrouwen',
  'de sinterklaas die duidelijk de buurman is',
  'de oliebol van drie dagen oud',
  'een partytent die wegwaait',
  'de klapstoel die het begeeft',
  'het springkussen op een barbecue voor volwassenen',
  'de kerstborrel met de directeur op de dansvloer',
  'een carnavalspak in juli',
  'de fiets die al twee jaar op het station staat',
  'een ov-chipkaart met nog negentig cent erop',
  'de slippers met sokken eronder',
  'de partytent die naar bier ruikt',
  'de opblaaskrokodil die de vijver op drijft',
  'een megafoon om zes uur in de ochtend',
  'de pruik die niet meer recht zit',
  'een confettikanon binnenshuis',
  'de rookmachine die het brandalarm activeert',
  'de tondeuse in verkeerde handen',
  'het lijmpistool en een heel slecht idee',
  'een waterpistool gevuld met iets anders',
  'de ladder die tegen het verkeerde raam stond',
  'de bodycam van iemand die te veel filmt',
  'de beveiligingsbeelden van de parkeergarage',
  'de nekbrace die niemand kan uitleggen',
  'krukken na een weddenschap van twee euro',
  'een parkeerboete op een trouwdag',
  'de pinpas die is ingeslikt door de automaat',
  'de sleutelbos in de gracht',
  'een taxichauffeur die weigert te rijden',
  'de nachtbus vol met mensen die naar hun werk gaan',
  'de uitsmijter die je naam kent',
  'iemand die lachgas doet en daarna filosofeert',
  'de kroegtijger die als laatste vertrekt',
  'een shotje dat naar benzine smaakt',
  'de tequila waar het altijd misgaat',
  'een blackout van drie uur',
  'de danspaal in een huiskamer',
  'de afterparty bij iemand die je niet kent',
  'de garderobebon die kwijt is',
  'een energiedrank op een lege maag',
  'het bierviltje met iemands nummer erop',
  'de braakemmer die doorgegeven wordt',
  'de kater die drie dagen duurt',
  'de groepsapp die om zeven uur ontploft',
  'de gedeelde locatie die stilstaat op een vreemd adres',
  'een ongelezen bericht van drie dagen oud',
  'de profielfoto van acht jaar geleden',
  'iemand die zijn zoekgeschiedenis vergeet te wissen',
  'de spraakmemo van elf minuten',
  'een screenshot dat naar de verkeerde ging',
  'de wifi-naam van de buren',
  'een bezorger die te veel gezien heeft',
  'de schoonmoeder die onaangekondigd langskomt',
  'de stiefvader die het gesprek aangaat',
  'een wijkagent met te veel interesse',
  'de tattoo met een spelfout',
  'de spiegel in de kleedkamer met slecht licht',
  'iemand die de sauna verkeerd begrepen heeft',
  'het naaktstrand met bekenden erop',
  'de zonnebrand in de vorm van een hand',
  'een invalidentoilet dat verkeerd gebruikt wordt',
  'de logeerkamer met veel te dunne muren',
  'iemand die de badkuip als bed gebruikt',
  'de dakgoot waar je niet meer uit komt',
  'het portiek waar iedereen doorheen loopt',
  'de draaideur die klem zit',
  'een kelder waar niemand heen wil',
  'de fietsenstalling om drie uur in de nacht',
  'de caravan van iemands opa',
  'de festivaltent die instort',
  'een wachtkamer met te veel oogcontact',
  'de achterbank met kruimels en spijt',
  'het politiebureau als eindpunt van de avond',
]
